package main

import (
	"context"
	"fmt"
	"net"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	redis "github.com/redis/go-redis/v9"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"eigenflux_server/kitex_gen/eigenflux/auth"
	"eigenflux_server/pkg/cache/keys"
	shareddb "eigenflux_server/pkg/db"
	"eigenflux_server/pkg/email"
	"eigenflux_server/pkg/mq"
	"eigenflux_server/rpc/auth/dal"
)

var authRetryV1ReleaseRedis = redis.NewScript(`
if redis.call('GET', KEYS[1]) ~= ARGV[1] then return 0 end
return redis.call('DEL', KEYS[1])
`)

// DB14 was empty before the lease was acquired, and each subtest creates only
// bounded fixture keys. Check ownership and delete atomically so a stale owner
// cannot clear a successor's keys after its lease expires.
var authRetryV1ClearRedis = redis.NewScript(`
if redis.call('GET', KEYS[1]) ~= ARGV[1] then return 0 end
local keys = redis.call('KEYS', '*')
if #keys > 256 then return -1 end
for _, key in ipairs(keys) do redis.call('DEL', key) end
return 1
`)

// The explicit endpoint variables opt into an owned loopback fixture. Redis
// DB14 is reserved for this suite; no default DB or public application row is
// written. Copy checks/indexes from current migrations, but give serial columns
// local identities so the copied defaults cannot advance public sequences.
func authRetryV1Fixture(t *testing.T) (*gorm.DB, *redis.Client, *AuthServiceImpl, string) {
	t.Helper()
	dsn, addr := os.Getenv("AUTH_RETRY_PG_DSN"), os.Getenv("AUTH_RETRY_REDIS_ADDR")
	if dsn == "" || addr == "" {
		t.Skip("AUTH_RETRY_PG_DSN and AUTH_RETRY_REDIS_ADDR are required for native OTP boundaries")
	}
	cfg, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatal("invalid OTP fixture PostgreSQL configuration")
	}
	host, _, err := net.SplitHostPort(addr)
	if err != nil || (host != "127.0.0.1" && host != "localhost" && host != "::1") ||
		(cfg.Host != "127.0.0.1" && cfg.Host != "localhost" && cfg.Host != "::1") {
		t.Fatal("OTP fixtures require explicit loopback PostgreSQL and Redis endpoints")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	rdb := redis.NewClient(&redis.Options{Addr: addr, DB: 14})
	owner := uuid.NewString()
	const lease = "arena:otp-retry:test-owner"
	for {
		locked, lockErr := rdb.SetNX(ctx, lease, owner, 2*time.Minute).Result()
		if lockErr != nil {
			rdb.Close()
			t.Fatalf("OTP fixture Redis unavailable: %v", lockErr)
		}
		if locked {
			break
		}
		select {
		case <-ctx.Done():
			rdb.Close()
			t.Fatal("OTP Redis DB14 is owned by another running test")
		case <-time.After(20 * time.Millisecond):
		}
	}
	if count, sizeErr := rdb.DBSize(ctx).Result(); sizeErr != nil || count != 1 {
		authRetryV1ReleaseRedis.Run(ctx, rdb, []string{lease}, owner)
		rdb.Close()
		t.Fatal("OTP Redis DB14 must be empty before its fixture lease is acquired")
	}
	t.Cleanup(func() {
		cleanup, stop := context.WithTimeout(context.Background(), 5*time.Second)
		defer stop()
		if cleared, err := authRetryV1ClearRedis.Run(cleanup, rdb, []string{lease}, owner).Int(); err != nil {
			t.Errorf("OTP DB14 cleanup failed: %v", err)
		} else if cleared != 1 {
			t.Error("lost ownership or unexpected key count in OTP Redis fixture; refusing to clear DB14")
		}
		rdb.Close()
	})
	admin, err := gorm.Open(postgres.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		t.Fatal(err)
	}
	adminSQL, err := admin.DB()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { adminSQL.Close() })
	schema := "otp_retry_v1_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	quoted := pgx.Identifier{schema}.Sanitize()
	if err := admin.Exec("CREATE SCHEMA " + quoted).Error; err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := admin.Exec("DROP SCHEMA " + quoted + " CASCADE").Error; err != nil {
			t.Errorf("OTP schema cleanup failed: %v", err)
		}
	})
	for _, table := range []string{"agents", "auth_email_challenges", "agent_sessions"} {
		name := pgx.Identifier{schema, table}.Sanitize()
		if err := admin.Exec("CREATE TABLE " + name + " (LIKE public." + pgx.Identifier{table}.Sanitize() + " INCLUDING ALL)").Error; err != nil {
			t.Fatal(err)
		}
		var columns []string
		if err := admin.Raw(`SELECT column_name FROM information_schema.columns
			WHERE table_schema = ? AND table_name = ? AND column_default LIKE 'nextval(%'`, schema, table).Scan(&columns).Error; err != nil {
			t.Fatal(err)
		}
		for _, column := range columns {
			col := pgx.Identifier{column}.Sanitize()
			if err := admin.Exec("ALTER TABLE " + name + " ALTER COLUMN " + col + " DROP DEFAULT, ALTER COLUMN " + col + " ADD GENERATED BY DEFAULT AS IDENTITY").Error; err != nil {
				t.Fatal(err)
			}
		}
	}
	cfg.RuntimeParams["search_path"] = schema
	cfg.RuntimeParams["statement_timeout"] = "5000"
	sqlDB := stdlib.OpenDB(*cfg)
	sqlDB.SetMaxOpenConns(12)
	gdb, err := gorm.Open(postgres.New(postgres.Config{Conn: sqlDB}), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		sqlDB.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() { sqlDB.Close() })
	priorDB, priorRedis := shareddb.DB, mq.RDB
	shareddb.DB, mq.RDB = gdb, rdb
	t.Cleanup(func() { shareddb.DB, mq.RDB = priorDB, priorRedis })
	emailAddr := "retry-" + uuid.NewString() + "@otp.invalid"
	agent := &dal.Agent{AgentID: 101, ShortID: "OtpAa", Email: emailAddr, EmailKind: "legacy_real", AgentName: "OTP Fixture", Bio: "isolated OTP test", CreatedAt: time.Now().UnixMilli(), UpdatedAt: time.Now().UnixMilli()}
	if err := gdb.Create(agent).Error; err != nil {
		t.Fatal(err)
	}
	svc := &AuthServiceImpl{emailVerificationEnabled: true, testEmailSuffixes: []string{"@otp.invalid"}, testOTP: "123456", emailSender: authRetryV1NoMail{}}
	return gdb, rdb, svc, emailAddr
}

type authRetryV1NoMail struct{}

var _ email.Sender = authRetryV1NoMail{}

func (authRetryV1NoMail) SendLoginVerifyMail(context.Context, string, string) error {
	return fmt.Errorf("OTP fixture must never send email")
}

func TestAuthRetryV1OTPBoundaries(t *testing.T) {
	for _, name := range []string{"retry_reuses_challenge", "expired_old_challenge", "attempt_limit", "single_consumption_and_cached_replay", "concurrent_start", "concurrent_verify", "concurrent_wrong_codes", "cleanup_refuses_stale_owner"} {
		t.Run(name, func(t *testing.T) {
			gdb, rdb, svc, emailAddr := authRetryV1Fixture(t)
			ctx := context.Background()
			start := func(address string) string {
				t.Helper()
				resp, err := svc.StartLogin(ctx, &auth.StartLoginReq{LoginMethod: "email", Email: address})
				if err != nil || resp == nil || resp.BaseResp == nil || resp.BaseResp.Code != 0 || resp.GetChallengeId() == "" {
					t.Fatalf("StartLogin failed: %#v, %v", resp, err)
				}
				return resp.GetChallengeId()
			}
			verify := func(id, code string) *auth.VerifyLoginResp {
				t.Helper()
				resp, err := svc.VerifyLogin(ctx, &auth.VerifyLoginReq{LoginMethod: "email", ChallengeId: id, Code: &code})
				if err != nil || resp == nil || resp.BaseResp == nil {
					t.Fatalf("VerifyLogin failed: %#v, %v", resp, err)
				}
				return resp
			}
			countSessions := func(want int64) {
				t.Helper()
				var count int64
				if err := gdb.Model(&dal.AgentSession{}).Count(&count).Error; err != nil || count != want {
					t.Fatalf("durable session count=%d want=%d err=%v", count, want, err)
				}
			}
			id := start(emailAddr)
			activeKey := "auth:login:email:active:" + sha256Hex(emailAddr)
			switch name {
			case "cleanup_refuses_stale_owner":
				const lease = "arena:otp-retry:test-owner"
				owner, err := rdb.Get(ctx, lease).Result()
				if err != nil {
					t.Fatal(err)
				}
				cached := rdb.Get(ctx, activeKey).Val()
				for _, script := range []*redis.Script{authRetryV1ReleaseRedis, authRetryV1ClearRedis} {
					if cleared, err := script.Run(ctx, rdb, []string{lease}, "expired-owner").Int(); err != nil || cleared != 0 {
						t.Fatalf("stale cleanup=%d err=%v", cleared, err)
					}
					if rdb.Get(ctx, lease).Val() != owner || rdb.Get(ctx, activeKey).Val() != cached || cached == "" {
						t.Fatal("stale owner deleted its successor's lease or challenge cache")
					}
				}
			case "retry_reuses_challenge":
				cached, err := rdb.Get(ctx, activeKey).Result()
				if err != nil {
					t.Fatal(err)
				}
				for i := 0; i < 3; i++ {
					if repeated := start("  " + strings.ToUpper(emailAddr) + "  "); repeated != id {
						t.Fatal("normalized retry replaced a live challenge")
					}
					if again := rdb.Get(ctx, activeKey).Val(); again != cached {
						t.Fatal("retry changed cached OTP")
					}
				}
				var count int64
				if err := gdb.Model(&dal.AuthEmailChallenge{}).Count(&count).Error; err != nil || count != 1 {
					t.Fatalf("challenge count=%d err=%v", count, err)
				}
				countSessions(0)
			case "expired_old_challenge":
				if err := gdb.Exec("UPDATE auth_email_challenges SET expire_at = ? WHERE challenge_id = ?", time.Now().Add(-time.Minute).UnixMilli(), id).Error; err != nil {
					t.Fatal(err)
				}
				fresh := start(emailAddr)
				if fresh == id {
					t.Fatal("expired challenge reused")
				}
				if resp := verify(id, "123456"); resp.BaseResp.Code != 400 || resp.BaseResp.Msg != "challenge has expired" {
					t.Fatalf("expired old challenge accepted: %#v", resp)
				}
				countSessions(0)
				if resp := verify(fresh, "123456"); resp.BaseResp.Code != 0 {
					t.Fatalf("fresh challenge rejected: %#v", resp)
				}
				countSessions(1)
			case "attempt_limit":
				for attempt := 1; attempt <= 5; attempt++ {
					if resp := verify(id, "000000"); resp.BaseResp.Code != 401 {
						t.Fatalf("wrong OTP attempt %d code=%d", attempt, resp.BaseResp.Code)
					}
					row, err := dal.GetChallenge(gdb, id)
					if err != nil || row.AttemptCount != attempt {
						t.Fatalf("attempts not durable: %#v err=%v", row, err)
					}
				}
				if resp := verify(id, "123456"); resp.BaseResp.Code != 400 {
					t.Fatalf("revoked OTP succeeded: %#v", resp)
				}
				row, _ := dal.GetChallenge(gdb, id)
				if row.Status != 3 || row.AttemptCount != 5 {
					t.Fatalf("attempt limit state=%#v", row)
				}
				countSessions(0)
				fresh := start(emailAddr)
				if fresh == id || verify(fresh, "123456").BaseResp.Code != 0 {
					t.Fatal("revoked challenge blocked a fresh request")
				}
			case "single_consumption_and_cached_replay":
				first := verify(id, "123456")
				if first.BaseResp.Code != 0 || first.AccessToken == "" {
					t.Fatal("first verification failed")
				}
				if replay := verify(id, "123456"); replay.BaseResp.Code != 0 || replay.AccessToken != first.AccessToken {
					t.Fatal("correct replay was not the same cached session")
				}
				if wrong := verify(id, "000000"); wrong.BaseResp.Code != 400 || wrong.AccessToken != "" {
					t.Fatal("wrong code unlocked a cached success")
				}
				cacheKey := keys.AuthVerify + id
				if ttl := rdb.PTTL(ctx, cacheKey).Val(); ttl <= 0 || ttl > 2*time.Minute {
					t.Fatalf("verify cache TTL=%v", ttl)
				}
				if err := rdb.PExpire(ctx, cacheKey, -time.Millisecond).Err(); err != nil {
					t.Fatal(err)
				}
				if afterCache := verify(id, "123456"); afterCache.BaseResp.Code != 400 {
					t.Fatal("consumed challenge reused after replay-cache expiry")
				}
				row, _ := dal.GetChallenge(gdb, id)
				if row.Status != 1 || row.ConsumedAt == nil {
					t.Fatal("consumption not durable")
				}
				if rdb.Exists(ctx, activeKey).Val() != 0 {
					t.Fatal("consumed challenge remains active for StartLogin")
				}
				countSessions(1)
			case "concurrent_start":
				// Start with an empty active slot to exercise real Redis SET NX.
				if err := gdb.Exec("DELETE FROM auth_email_challenges WHERE challenge_id = ?", id).Error; err != nil {
					t.Fatal(err)
				}
				if err := rdb.Del(ctx, activeKey).Err(); err != nil {
					t.Fatal(err)
				}
				ids := make(chan string, 8)
				gate := make(chan struct{})
				var workers sync.WaitGroup
				for i := 0; i < 8; i++ {
					workers.Add(1)
					go func() { defer workers.Done(); <-gate; ids <- start(emailAddr) }()
				}
				close(gate)
				workers.Wait()
				close(ids)
				winner := ""
				for got := range ids {
					if winner == "" {
						winner = got
					}
					if got != winner {
						t.Fatal("concurrent starts returned different active challenges")
					}
				}
				var pending int64
				if err := gdb.Model(&dal.AuthEmailChallenge{}).Where("status = 0").Count(&pending).Error; err != nil || pending != 1 {
					t.Fatalf("pending challenges=%d err=%v", pending, err)
				}
				countSessions(0)
			case "concurrent_verify", "concurrent_wrong_codes":
				code, n := "123456", 8
				if name == "concurrent_wrong_codes" {
					code, n = "000000", 5
				}
				responses := make(chan *auth.VerifyLoginResp, n)
				gate := make(chan struct{})
				var workers sync.WaitGroup
				for i := 0; i < n; i++ {
					workers.Add(1)
					go func() { defer workers.Done(); <-gate; responses <- verify(id, code) }()
				}
				close(gate)
				workers.Wait()
				close(responses)
				var successfulToken string
				for resp := range responses {
					if name == "concurrent_wrong_codes" {
						if resp.BaseResp.Code != 401 {
							t.Fatalf("wrong-code concurrent result=%d", resp.BaseResp.Code)
						}
						continue
					}
					if resp.BaseResp.Code == 0 {
						if successfulToken == "" {
							successfulToken = resp.AccessToken
						}
						if resp.AccessToken == "" || resp.AccessToken != successfulToken {
							t.Fatal("concurrent verification issued distinct sessions")
						}
					} else if resp.BaseResp.Code != 400 || resp.AccessToken != "" {
						t.Fatalf("unexpected concurrent rejection: %#v", resp)
					}
				}
				if name == "concurrent_wrong_codes" {
					row, _ := dal.GetChallenge(gdb, id)
					if row.Status != 3 || row.AttemptCount != 5 || verify(id, "123456").BaseResp.Code != 400 {
						t.Fatalf("concurrent attempts bypassed cap: %#v", row)
					}
					countSessions(0)
				} else {
					if successfulToken == "" {
						t.Fatal("no concurrent verification succeeded")
					}
					countSessions(1)
					if replay := verify(id, "123456"); replay.BaseResp.Code != 0 || replay.AccessToken != successfulToken {
						t.Fatal("post-race replay lost the successful session")
					}
				}
			}
		})
	}
}
