// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	eigenflux_console "console.eigenflux.ai/biz/router/eigenflux/console"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	eigenflux_console.Register(r)
}
