// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type CommissionStatistics struct {
	CommissionId          int64 `thrift:"commission_id,1" frugal:"1,default,i64" json:"commission_id"`
	SellerAgentId         int64 `thrift:"seller_agent_id,2" frugal:"2,default,i64" json:"seller_agent_id"`
	EstablishedCount      int64 `thrift:"established_count,3" frugal:"3,default,i64" json:"established_count"`
	CompletedCount        int64 `thrift:"completed_count,4" frugal:"4,default,i64" json:"completed_count"`
	RefundedCount         int64 `thrift:"refunded_count,5" frugal:"5,default,i64" json:"refunded_count"`
	DeliveryDurationSumMs int64 `thrift:"delivery_duration_sum_ms,6" frugal:"6,default,i64" json:"delivery_duration_sum_ms"`
	DeliveryDurationCount int64 `thrift:"delivery_duration_count,7" frugal:"7,default,i64" json:"delivery_duration_count"`
	AverageDeliveryMs     int64 `thrift:"average_delivery_ms,8" frugal:"8,default,i64" json:"average_delivery_ms"`
	CompletionRateBps     int32 `thrift:"completion_rate_bps,9" frugal:"9,default,i32" json:"completion_rate_bps"`
	RatingSum             int64 `thrift:"rating_sum,10" frugal:"10,default,i64" json:"rating_sum"`
	RatingCount           int64 `thrift:"rating_count,11" frugal:"11,default,i64" json:"rating_count"`
	AverageRatingMilli    int32 `thrift:"average_rating_milli,12" frugal:"12,default,i32" json:"average_rating_milli"`
	HasRating             bool  `thrift:"has_rating,13" frugal:"13,default,bool" json:"has_rating"`
	LastActivityAt        int64 `thrift:"last_activity_at,14" frugal:"14,default,i64" json:"last_activity_at"`
	StatisticsVersion     int64 `thrift:"statistics_version,15" frugal:"15,default,i64" json:"statistics_version"`
}

func NewCommissionStatistics() *CommissionStatistics {
	return &CommissionStatistics{}
}

func (p *CommissionStatistics) InitDefault() {
}

func (p *CommissionStatistics) GetCommissionId() (v int64) {
	return p.CommissionId
}

func (p *CommissionStatistics) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *CommissionStatistics) GetEstablishedCount() (v int64) {
	return p.EstablishedCount
}

func (p *CommissionStatistics) GetCompletedCount() (v int64) {
	return p.CompletedCount
}

func (p *CommissionStatistics) GetRefundedCount() (v int64) {
	return p.RefundedCount
}

func (p *CommissionStatistics) GetDeliveryDurationSumMs() (v int64) {
	return p.DeliveryDurationSumMs
}

func (p *CommissionStatistics) GetDeliveryDurationCount() (v int64) {
	return p.DeliveryDurationCount
}

func (p *CommissionStatistics) GetAverageDeliveryMs() (v int64) {
	return p.AverageDeliveryMs
}

func (p *CommissionStatistics) GetCompletionRateBps() (v int32) {
	return p.CompletionRateBps
}

func (p *CommissionStatistics) GetRatingSum() (v int64) {
	return p.RatingSum
}

func (p *CommissionStatistics) GetRatingCount() (v int64) {
	return p.RatingCount
}

func (p *CommissionStatistics) GetAverageRatingMilli() (v int32) {
	return p.AverageRatingMilli
}

func (p *CommissionStatistics) GetHasRating() (v bool) {
	return p.HasRating
}

func (p *CommissionStatistics) GetLastActivityAt() (v int64) {
	return p.LastActivityAt
}

func (p *CommissionStatistics) GetStatisticsVersion() (v int64) {
	return p.StatisticsVersion
}
func (p *CommissionStatistics) SetCommissionId(val int64) {
	p.CommissionId = val
}
func (p *CommissionStatistics) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *CommissionStatistics) SetEstablishedCount(val int64) {
	p.EstablishedCount = val
}
func (p *CommissionStatistics) SetCompletedCount(val int64) {
	p.CompletedCount = val
}
func (p *CommissionStatistics) SetRefundedCount(val int64) {
	p.RefundedCount = val
}
func (p *CommissionStatistics) SetDeliveryDurationSumMs(val int64) {
	p.DeliveryDurationSumMs = val
}
func (p *CommissionStatistics) SetDeliveryDurationCount(val int64) {
	p.DeliveryDurationCount = val
}
func (p *CommissionStatistics) SetAverageDeliveryMs(val int64) {
	p.AverageDeliveryMs = val
}
func (p *CommissionStatistics) SetCompletionRateBps(val int32) {
	p.CompletionRateBps = val
}
func (p *CommissionStatistics) SetRatingSum(val int64) {
	p.RatingSum = val
}
func (p *CommissionStatistics) SetRatingCount(val int64) {
	p.RatingCount = val
}
func (p *CommissionStatistics) SetAverageRatingMilli(val int32) {
	p.AverageRatingMilli = val
}
func (p *CommissionStatistics) SetHasRating(val bool) {
	p.HasRating = val
}
func (p *CommissionStatistics) SetLastActivityAt(val int64) {
	p.LastActivityAt = val
}
func (p *CommissionStatistics) SetStatisticsVersion(val int64) {
	p.StatisticsVersion = val
}

func (p *CommissionStatistics) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommissionStatistics(%+v)", *p)
}

var fieldIDToName_CommissionStatistics = map[int16]string{
	1:  "commission_id",
	2:  "seller_agent_id",
	3:  "established_count",
	4:  "completed_count",
	5:  "refunded_count",
	6:  "delivery_duration_sum_ms",
	7:  "delivery_duration_count",
	8:  "average_delivery_ms",
	9:  "completion_rate_bps",
	10: "rating_sum",
	11: "rating_count",
	12: "average_rating_milli",
	13: "has_rating",
	14: "last_activity_at",
	15: "statistics_version",
}

type GetCommissionStatisticsReq struct {
	CommissionId int64 `thrift:"commission_id,1" frugal:"1,default,i64" json:"commission_id"`
}

func NewGetCommissionStatisticsReq() *GetCommissionStatisticsReq {
	return &GetCommissionStatisticsReq{}
}

func (p *GetCommissionStatisticsReq) InitDefault() {
}

func (p *GetCommissionStatisticsReq) GetCommissionId() (v int64) {
	return p.CommissionId
}
func (p *GetCommissionStatisticsReq) SetCommissionId(val int64) {
	p.CommissionId = val
}

func (p *GetCommissionStatisticsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCommissionStatisticsReq(%+v)", *p)
}

var fieldIDToName_GetCommissionStatisticsReq = map[int16]string{
	1: "commission_id",
}

type GetCommissionStatisticsResp struct {
	Statistics *CommissionStatistics `thrift:"statistics,1" frugal:"1,default,CommissionStatistics" json:"statistics"`
	BaseResp   *base.BaseResp        `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetCommissionStatisticsResp() *GetCommissionStatisticsResp {
	return &GetCommissionStatisticsResp{}
}

func (p *GetCommissionStatisticsResp) InitDefault() {
}

var GetCommissionStatisticsResp_Statistics_DEFAULT *CommissionStatistics

func (p *GetCommissionStatisticsResp) GetStatistics() (v *CommissionStatistics) {
	if !p.IsSetStatistics() {
		return GetCommissionStatisticsResp_Statistics_DEFAULT
	}
	return p.Statistics
}

var GetCommissionStatisticsResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetCommissionStatisticsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetCommissionStatisticsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetCommissionStatisticsResp) SetStatistics(val *CommissionStatistics) {
	p.Statistics = val
}
func (p *GetCommissionStatisticsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetCommissionStatisticsResp) IsSetStatistics() bool {
	return p.Statistics != nil
}

func (p *GetCommissionStatisticsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetCommissionStatisticsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCommissionStatisticsResp(%+v)", *p)
}

var fieldIDToName_GetCommissionStatisticsResp = map[int16]string{
	1:   "statistics",
	255: "base_resp",
}

type BatchGetCommissionStatisticsReq struct {
	CommissionIds []int64 `thrift:"commission_ids,1" frugal:"1,default,list<i64>" json:"commission_ids"`
}

func NewBatchGetCommissionStatisticsReq() *BatchGetCommissionStatisticsReq {
	return &BatchGetCommissionStatisticsReq{}
}

func (p *BatchGetCommissionStatisticsReq) InitDefault() {
}

func (p *BatchGetCommissionStatisticsReq) GetCommissionIds() (v []int64) {
	return p.CommissionIds
}
func (p *BatchGetCommissionStatisticsReq) SetCommissionIds(val []int64) {
	p.CommissionIds = val
}

func (p *BatchGetCommissionStatisticsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetCommissionStatisticsReq(%+v)", *p)
}

var fieldIDToName_BatchGetCommissionStatisticsReq = map[int16]string{
	1: "commission_ids",
}

type BatchGetCommissionStatisticsResp struct {
	Statistics []*CommissionStatistics `thrift:"statistics,1" frugal:"1,default,list<CommissionStatistics>" json:"statistics"`
	BaseResp   *base.BaseResp          `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewBatchGetCommissionStatisticsResp() *BatchGetCommissionStatisticsResp {
	return &BatchGetCommissionStatisticsResp{}
}

func (p *BatchGetCommissionStatisticsResp) InitDefault() {
}

func (p *BatchGetCommissionStatisticsResp) GetStatistics() (v []*CommissionStatistics) {
	return p.Statistics
}

var BatchGetCommissionStatisticsResp_BaseResp_DEFAULT *base.BaseResp

func (p *BatchGetCommissionStatisticsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return BatchGetCommissionStatisticsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *BatchGetCommissionStatisticsResp) SetStatistics(val []*CommissionStatistics) {
	p.Statistics = val
}
func (p *BatchGetCommissionStatisticsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *BatchGetCommissionStatisticsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BatchGetCommissionStatisticsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetCommissionStatisticsResp(%+v)", *p)
}

var fieldIDToName_BatchGetCommissionStatisticsResp = map[int16]string{
	1:   "statistics",
	255: "base_resp",
}

type OrderService interface {
	GetCommissionStatistics(ctx context.Context, req *GetCommissionStatisticsReq) (r *GetCommissionStatisticsResp, err error)

	BatchGetCommissionStatistics(ctx context.Context, req *BatchGetCommissionStatisticsReq) (r *BatchGetCommissionStatisticsResp, err error)
}

type OrderServiceGetCommissionStatisticsArgs struct {
	Req *GetCommissionStatisticsReq `thrift:"req,1" frugal:"1,default,GetCommissionStatisticsReq" json:"req"`
}

func NewOrderServiceGetCommissionStatisticsArgs() *OrderServiceGetCommissionStatisticsArgs {
	return &OrderServiceGetCommissionStatisticsArgs{}
}

func (p *OrderServiceGetCommissionStatisticsArgs) InitDefault() {
}

var OrderServiceGetCommissionStatisticsArgs_Req_DEFAULT *GetCommissionStatisticsReq

func (p *OrderServiceGetCommissionStatisticsArgs) GetReq() (v *GetCommissionStatisticsReq) {
	if !p.IsSetReq() {
		return OrderServiceGetCommissionStatisticsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetCommissionStatisticsArgs) SetReq(val *GetCommissionStatisticsReq) {
	p.Req = val
}

func (p *OrderServiceGetCommissionStatisticsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetCommissionStatisticsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetCommissionStatisticsArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetCommissionStatisticsArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetCommissionStatisticsResult struct {
	Success *GetCommissionStatisticsResp `thrift:"success,0,optional" frugal:"0,optional,GetCommissionStatisticsResp" json:"success,omitempty"`
}

func NewOrderServiceGetCommissionStatisticsResult() *OrderServiceGetCommissionStatisticsResult {
	return &OrderServiceGetCommissionStatisticsResult{}
}

func (p *OrderServiceGetCommissionStatisticsResult) InitDefault() {
}

var OrderServiceGetCommissionStatisticsResult_Success_DEFAULT *GetCommissionStatisticsResp

func (p *OrderServiceGetCommissionStatisticsResult) GetSuccess() (v *GetCommissionStatisticsResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetCommissionStatisticsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetCommissionStatisticsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCommissionStatisticsResp)
}

func (p *OrderServiceGetCommissionStatisticsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetCommissionStatisticsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetCommissionStatisticsResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetCommissionStatisticsResult = map[int16]string{
	0: "success",
}

type OrderServiceBatchGetCommissionStatisticsArgs struct {
	Req *BatchGetCommissionStatisticsReq `thrift:"req,1" frugal:"1,default,BatchGetCommissionStatisticsReq" json:"req"`
}

func NewOrderServiceBatchGetCommissionStatisticsArgs() *OrderServiceBatchGetCommissionStatisticsArgs {
	return &OrderServiceBatchGetCommissionStatisticsArgs{}
}

func (p *OrderServiceBatchGetCommissionStatisticsArgs) InitDefault() {
}

var OrderServiceBatchGetCommissionStatisticsArgs_Req_DEFAULT *BatchGetCommissionStatisticsReq

func (p *OrderServiceBatchGetCommissionStatisticsArgs) GetReq() (v *BatchGetCommissionStatisticsReq) {
	if !p.IsSetReq() {
		return OrderServiceBatchGetCommissionStatisticsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceBatchGetCommissionStatisticsArgs) SetReq(val *BatchGetCommissionStatisticsReq) {
	p.Req = val
}

func (p *OrderServiceBatchGetCommissionStatisticsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceBatchGetCommissionStatisticsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceBatchGetCommissionStatisticsArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceBatchGetCommissionStatisticsArgs = map[int16]string{
	1: "req",
}

type OrderServiceBatchGetCommissionStatisticsResult struct {
	Success *BatchGetCommissionStatisticsResp `thrift:"success,0,optional" frugal:"0,optional,BatchGetCommissionStatisticsResp" json:"success,omitempty"`
}

func NewOrderServiceBatchGetCommissionStatisticsResult() *OrderServiceBatchGetCommissionStatisticsResult {
	return &OrderServiceBatchGetCommissionStatisticsResult{}
}

func (p *OrderServiceBatchGetCommissionStatisticsResult) InitDefault() {
}

var OrderServiceBatchGetCommissionStatisticsResult_Success_DEFAULT *BatchGetCommissionStatisticsResp

func (p *OrderServiceBatchGetCommissionStatisticsResult) GetSuccess() (v *BatchGetCommissionStatisticsResp) {
	if !p.IsSetSuccess() {
		return OrderServiceBatchGetCommissionStatisticsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceBatchGetCommissionStatisticsResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchGetCommissionStatisticsResp)
}

func (p *OrderServiceBatchGetCommissionStatisticsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceBatchGetCommissionStatisticsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceBatchGetCommissionStatisticsResult(%+v)", *p)
}

var fieldIDToName_OrderServiceBatchGetCommissionStatisticsResult = map[int16]string{
	0: "success",
}
