// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package feed

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type FeedItem struct {
	ItemId           int64    `thrift:"item_id,1,required" frugal:"1,required,i64" json:"item_id"`
	Summary          *string  `thrift:"summary,2,optional" frugal:"2,optional,string" json:"summary,omitempty"`
	BroadcastType    string   `thrift:"broadcast_type,3,required" frugal:"3,required,string" json:"broadcast_type"`
	Domains          []string `thrift:"domains,4,optional" frugal:"4,optional,list<string>" json:"domains,omitempty"`
	Keywords         []string `thrift:"keywords,5,optional" frugal:"5,optional,list<string>" json:"keywords,omitempty"`
	ExpireTime       *string  `thrift:"expire_time,6,optional" frugal:"6,optional,string" json:"expire_time,omitempty"`
	Geo              *string  `thrift:"geo,7,optional" frugal:"7,optional,string" json:"geo,omitempty"`
	SourceType       *string  `thrift:"source_type,8,optional" frugal:"8,optional,string" json:"source_type,omitempty"`
	ExpectedResponse *string  `thrift:"expected_response,9,optional" frugal:"9,optional,string" json:"expected_response,omitempty"`
	GroupId          *int64   `thrift:"group_id,10,optional" frugal:"10,optional,i64" json:"group_id,omitempty"`
	UpdatedAt        int64    `thrift:"updated_at,11,required" frugal:"11,required,i64" json:"updated_at"`
}

func NewFeedItem() *FeedItem {
	return &FeedItem{}
}

func (p *FeedItem) InitDefault() {
}

func (p *FeedItem) GetItemId() (v int64) {
	return p.ItemId
}

var FeedItem_Summary_DEFAULT string

func (p *FeedItem) GetSummary() (v string) {
	if !p.IsSetSummary() {
		return FeedItem_Summary_DEFAULT
	}
	return *p.Summary
}

func (p *FeedItem) GetBroadcastType() (v string) {
	return p.BroadcastType
}

var FeedItem_Domains_DEFAULT []string

func (p *FeedItem) GetDomains() (v []string) {
	if !p.IsSetDomains() {
		return FeedItem_Domains_DEFAULT
	}
	return p.Domains
}

var FeedItem_Keywords_DEFAULT []string

func (p *FeedItem) GetKeywords() (v []string) {
	if !p.IsSetKeywords() {
		return FeedItem_Keywords_DEFAULT
	}
	return p.Keywords
}

var FeedItem_ExpireTime_DEFAULT string

func (p *FeedItem) GetExpireTime() (v string) {
	if !p.IsSetExpireTime() {
		return FeedItem_ExpireTime_DEFAULT
	}
	return *p.ExpireTime
}

var FeedItem_Geo_DEFAULT string

func (p *FeedItem) GetGeo() (v string) {
	if !p.IsSetGeo() {
		return FeedItem_Geo_DEFAULT
	}
	return *p.Geo
}

var FeedItem_SourceType_DEFAULT string

func (p *FeedItem) GetSourceType() (v string) {
	if !p.IsSetSourceType() {
		return FeedItem_SourceType_DEFAULT
	}
	return *p.SourceType
}

var FeedItem_ExpectedResponse_DEFAULT string

func (p *FeedItem) GetExpectedResponse() (v string) {
	if !p.IsSetExpectedResponse() {
		return FeedItem_ExpectedResponse_DEFAULT
	}
	return *p.ExpectedResponse
}

var FeedItem_GroupId_DEFAULT int64

func (p *FeedItem) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return FeedItem_GroupId_DEFAULT
	}
	return *p.GroupId
}

func (p *FeedItem) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *FeedItem) SetItemId(val int64) {
	p.ItemId = val
}
func (p *FeedItem) SetSummary(val *string) {
	p.Summary = val
}
func (p *FeedItem) SetBroadcastType(val string) {
	p.BroadcastType = val
}
func (p *FeedItem) SetDomains(val []string) {
	p.Domains = val
}
func (p *FeedItem) SetKeywords(val []string) {
	p.Keywords = val
}
func (p *FeedItem) SetExpireTime(val *string) {
	p.ExpireTime = val
}
func (p *FeedItem) SetGeo(val *string) {
	p.Geo = val
}
func (p *FeedItem) SetSourceType(val *string) {
	p.SourceType = val
}
func (p *FeedItem) SetExpectedResponse(val *string) {
	p.ExpectedResponse = val
}
func (p *FeedItem) SetGroupId(val *int64) {
	p.GroupId = val
}
func (p *FeedItem) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *FeedItem) IsSetSummary() bool {
	return p.Summary != nil
}

func (p *FeedItem) IsSetDomains() bool {
	return p.Domains != nil
}

func (p *FeedItem) IsSetKeywords() bool {
	return p.Keywords != nil
}

func (p *FeedItem) IsSetExpireTime() bool {
	return p.ExpireTime != nil
}

func (p *FeedItem) IsSetGeo() bool {
	return p.Geo != nil
}

func (p *FeedItem) IsSetSourceType() bool {
	return p.SourceType != nil
}

func (p *FeedItem) IsSetExpectedResponse() bool {
	return p.ExpectedResponse != nil
}

func (p *FeedItem) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *FeedItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedItem(%+v)", *p)
}

var fieldIDToName_FeedItem = map[int16]string{
	1:  "item_id",
	2:  "summary",
	3:  "broadcast_type",
	4:  "domains",
	5:  "keywords",
	6:  "expire_time",
	7:  "geo",
	8:  "source_type",
	9:  "expected_response",
	10: "group_id",
	11: "updated_at",
}

type Notification struct {
	NotificationId int64  `thrift:"notification_id,1,required" frugal:"1,required,i64" json:"notification_id"`
	Type           string `thrift:"type,2,required" frugal:"2,required,string" json:"type"`
	Content        string `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
	CreatedAt      int64  `thrift:"created_at,4,required" frugal:"4,required,i64" json:"created_at"`
	SourceType     string `thrift:"source_type,5,required" frugal:"5,required,string" json:"source_type"`
}

func NewNotification() *Notification {
	return &Notification{}
}

func (p *Notification) InitDefault() {
}

func (p *Notification) GetNotificationId() (v int64) {
	return p.NotificationId
}

func (p *Notification) GetType() (v string) {
	return p.Type
}

func (p *Notification) GetContent() (v string) {
	return p.Content
}

func (p *Notification) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Notification) GetSourceType() (v string) {
	return p.SourceType
}
func (p *Notification) SetNotificationId(val int64) {
	p.NotificationId = val
}
func (p *Notification) SetType(val string) {
	p.Type = val
}
func (p *Notification) SetContent(val string) {
	p.Content = val
}
func (p *Notification) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Notification) SetSourceType(val string) {
	p.SourceType = val
}

func (p *Notification) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Notification(%+v)", *p)
}

var fieldIDToName_Notification = map[int16]string{
	1: "notification_id",
	2: "type",
	3: "content",
	4: "created_at",
	5: "source_type",
}

type AckNotificationItem struct {
	NotificationId int64  `thrift:"notification_id,1,required" frugal:"1,required,i64" json:"notification_id"`
	SourceType     string `thrift:"source_type,2,required" frugal:"2,required,string" json:"source_type"`
}

func NewAckNotificationItem() *AckNotificationItem {
	return &AckNotificationItem{}
}

func (p *AckNotificationItem) InitDefault() {
}

func (p *AckNotificationItem) GetNotificationId() (v int64) {
	return p.NotificationId
}

func (p *AckNotificationItem) GetSourceType() (v string) {
	return p.SourceType
}
func (p *AckNotificationItem) SetNotificationId(val int64) {
	p.NotificationId = val
}
func (p *AckNotificationItem) SetSourceType(val string) {
	p.SourceType = val
}

func (p *AckNotificationItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationItem(%+v)", *p)
}

var fieldIDToName_AckNotificationItem = map[int16]string{
	1: "notification_id",
	2: "source_type",
}

type FetchFeedReq struct {
	AgentId int64   `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Action  *string `thrift:"action,2,optional" frugal:"2,optional,string" json:"action,omitempty"`
	Limit   *int32  `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
}

func NewFetchFeedReq() *FetchFeedReq {
	return &FetchFeedReq{}
}

func (p *FetchFeedReq) InitDefault() {
}

func (p *FetchFeedReq) GetAgentId() (v int64) {
	return p.AgentId
}

var FetchFeedReq_Action_DEFAULT string

func (p *FetchFeedReq) GetAction() (v string) {
	if !p.IsSetAction() {
		return FetchFeedReq_Action_DEFAULT
	}
	return *p.Action
}

var FetchFeedReq_Limit_DEFAULT int32

func (p *FetchFeedReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return FetchFeedReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *FetchFeedReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *FetchFeedReq) SetAction(val *string) {
	p.Action = val
}
func (p *FetchFeedReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *FetchFeedReq) IsSetAction() bool {
	return p.Action != nil
}

func (p *FetchFeedReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *FetchFeedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchFeedReq(%+v)", *p)
}

var fieldIDToName_FetchFeedReq = map[int16]string{
	1: "agent_id",
	2: "action",
	3: "limit",
}

type FetchFeedResp struct {
	Items         []*FeedItem     `thrift:"items,1,required" frugal:"1,required,list<FeedItem>" json:"items"`
	HasMore       bool            `thrift:"has_more,2,required" frugal:"2,required,bool" json:"has_more"`
	Notifications []*Notification `thrift:"notifications,3,optional" frugal:"3,optional,list<Notification>" json:"notifications,omitempty"`
	BaseResp      *base.BaseResp  `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewFetchFeedResp() *FetchFeedResp {
	return &FetchFeedResp{}
}

func (p *FetchFeedResp) InitDefault() {
}

func (p *FetchFeedResp) GetItems() (v []*FeedItem) {
	return p.Items
}

func (p *FetchFeedResp) GetHasMore() (v bool) {
	return p.HasMore
}

var FetchFeedResp_Notifications_DEFAULT []*Notification

func (p *FetchFeedResp) GetNotifications() (v []*Notification) {
	if !p.IsSetNotifications() {
		return FetchFeedResp_Notifications_DEFAULT
	}
	return p.Notifications
}

var FetchFeedResp_BaseResp_DEFAULT *base.BaseResp

func (p *FetchFeedResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return FetchFeedResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *FetchFeedResp) SetItems(val []*FeedItem) {
	p.Items = val
}
func (p *FetchFeedResp) SetHasMore(val bool) {
	p.HasMore = val
}
func (p *FetchFeedResp) SetNotifications(val []*Notification) {
	p.Notifications = val
}
func (p *FetchFeedResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *FetchFeedResp) IsSetNotifications() bool {
	return p.Notifications != nil
}

func (p *FetchFeedResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FetchFeedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchFeedResp(%+v)", *p)
}

var fieldIDToName_FetchFeedResp = map[int16]string{
	1:   "items",
	2:   "has_more",
	3:   "notifications",
	255: "base_resp",
}

type AckNotificationsReq struct {
	AgentId int64                  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Items   []*AckNotificationItem `thrift:"items,2,required" frugal:"2,required,list<AckNotificationItem>" json:"items"`
}

func NewAckNotificationsReq() *AckNotificationsReq {
	return &AckNotificationsReq{}
}

func (p *AckNotificationsReq) InitDefault() {
}

func (p *AckNotificationsReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *AckNotificationsReq) GetItems() (v []*AckNotificationItem) {
	return p.Items
}
func (p *AckNotificationsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *AckNotificationsReq) SetItems(val []*AckNotificationItem) {
	p.Items = val
}

func (p *AckNotificationsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationsReq(%+v)", *p)
}

var fieldIDToName_AckNotificationsReq = map[int16]string{
	1: "agent_id",
	2: "items",
}

type AckNotificationsResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewAckNotificationsResp() *AckNotificationsResp {
	return &AckNotificationsResp{}
}

func (p *AckNotificationsResp) InitDefault() {
}

var AckNotificationsResp_BaseResp_DEFAULT *base.BaseResp

func (p *AckNotificationsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return AckNotificationsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *AckNotificationsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *AckNotificationsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AckNotificationsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationsResp(%+v)", *p)
}

var fieldIDToName_AckNotificationsResp = map[int16]string{
	255: "base_resp",
}

type FeedService interface {
	FetchFeed(ctx context.Context, req *FetchFeedReq) (r *FetchFeedResp, err error)

	AckNotifications(ctx context.Context, req *AckNotificationsReq) (r *AckNotificationsResp, err error)
}

type FeedServiceFetchFeedArgs struct {
	Req *FetchFeedReq `thrift:"req,1" frugal:"1,default,FetchFeedReq" json:"req"`
}

func NewFeedServiceFetchFeedArgs() *FeedServiceFetchFeedArgs {
	return &FeedServiceFetchFeedArgs{}
}

func (p *FeedServiceFetchFeedArgs) InitDefault() {
}

var FeedServiceFetchFeedArgs_Req_DEFAULT *FetchFeedReq

func (p *FeedServiceFetchFeedArgs) GetReq() (v *FetchFeedReq) {
	if !p.IsSetReq() {
		return FeedServiceFetchFeedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *FeedServiceFetchFeedArgs) SetReq(val *FetchFeedReq) {
	p.Req = val
}

func (p *FeedServiceFetchFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FeedServiceFetchFeedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedServiceFetchFeedArgs(%+v)", *p)
}

var fieldIDToName_FeedServiceFetchFeedArgs = map[int16]string{
	1: "req",
}

type FeedServiceFetchFeedResult struct {
	Success *FetchFeedResp `thrift:"success,0,optional" frugal:"0,optional,FetchFeedResp" json:"success,omitempty"`
}

func NewFeedServiceFetchFeedResult() *FeedServiceFetchFeedResult {
	return &FeedServiceFetchFeedResult{}
}

func (p *FeedServiceFetchFeedResult) InitDefault() {
}

var FeedServiceFetchFeedResult_Success_DEFAULT *FetchFeedResp

func (p *FeedServiceFetchFeedResult) GetSuccess() (v *FetchFeedResp) {
	if !p.IsSetSuccess() {
		return FeedServiceFetchFeedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *FeedServiceFetchFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*FetchFeedResp)
}

func (p *FeedServiceFetchFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FeedServiceFetchFeedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedServiceFetchFeedResult(%+v)", *p)
}

var fieldIDToName_FeedServiceFetchFeedResult = map[int16]string{
	0: "success",
}

type FeedServiceAckNotificationsArgs struct {
	Req *AckNotificationsReq `thrift:"req,1" frugal:"1,default,AckNotificationsReq" json:"req"`
}

func NewFeedServiceAckNotificationsArgs() *FeedServiceAckNotificationsArgs {
	return &FeedServiceAckNotificationsArgs{}
}

func (p *FeedServiceAckNotificationsArgs) InitDefault() {
}

var FeedServiceAckNotificationsArgs_Req_DEFAULT *AckNotificationsReq

func (p *FeedServiceAckNotificationsArgs) GetReq() (v *AckNotificationsReq) {
	if !p.IsSetReq() {
		return FeedServiceAckNotificationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *FeedServiceAckNotificationsArgs) SetReq(val *AckNotificationsReq) {
	p.Req = val
}

func (p *FeedServiceAckNotificationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FeedServiceAckNotificationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedServiceAckNotificationsArgs(%+v)", *p)
}

var fieldIDToName_FeedServiceAckNotificationsArgs = map[int16]string{
	1: "req",
}

type FeedServiceAckNotificationsResult struct {
	Success *AckNotificationsResp `thrift:"success,0,optional" frugal:"0,optional,AckNotificationsResp" json:"success,omitempty"`
}

func NewFeedServiceAckNotificationsResult() *FeedServiceAckNotificationsResult {
	return &FeedServiceAckNotificationsResult{}
}

func (p *FeedServiceAckNotificationsResult) InitDefault() {
}

var FeedServiceAckNotificationsResult_Success_DEFAULT *AckNotificationsResp

func (p *FeedServiceAckNotificationsResult) GetSuccess() (v *AckNotificationsResp) {
	if !p.IsSetSuccess() {
		return FeedServiceAckNotificationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *FeedServiceAckNotificationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*AckNotificationsResp)
}

func (p *FeedServiceAckNotificationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FeedServiceAckNotificationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedServiceAckNotificationsResult(%+v)", *p)
}

var fieldIDToName_FeedServiceAckNotificationsResult = map[int16]string{
	0: "success",
}
