// Code generated by Kitex v0.16.1. DO NOT EDIT.

package pmservice

import (
	"context"
	pm "eigenflux_server/kitex_gen/eigenflux/pm"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendPM(ctx context.Context, req *pm.SendPMReq, callOptions ...callopt.Option) (r *pm.SendPMResp, err error)
	FetchPM(ctx context.Context, req *pm.FetchPMReq, callOptions ...callopt.Option) (r *pm.FetchPMResp, err error)
	ListConversations(ctx context.Context, req *pm.ListConversationsReq, callOptions ...callopt.Option) (r *pm.ListConversationsResp, err error)
	GetConvHistory(ctx context.Context, req *pm.GetConvHistoryReq, callOptions ...callopt.Option) (r *pm.GetConvHistoryResp, err error)
	CloseConv(ctx context.Context, req *pm.CloseConvReq, callOptions ...callopt.Option) (r *pm.CloseConvResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPMServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPMServiceClient struct {
	*kClient
}

func (p *kPMServiceClient) SendPM(ctx context.Context, req *pm.SendPMReq, callOptions ...callopt.Option) (r *pm.SendPMResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendPM(ctx, req)
}

func (p *kPMServiceClient) FetchPM(ctx context.Context, req *pm.FetchPMReq, callOptions ...callopt.Option) (r *pm.FetchPMResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchPM(ctx, req)
}

func (p *kPMServiceClient) ListConversations(ctx context.Context, req *pm.ListConversationsReq, callOptions ...callopt.Option) (r *pm.ListConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversations(ctx, req)
}

func (p *kPMServiceClient) GetConvHistory(ctx context.Context, req *pm.GetConvHistoryReq, callOptions ...callopt.Option) (r *pm.GetConvHistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConvHistory(ctx, req)
}

func (p *kPMServiceClient) CloseConv(ctx context.Context, req *pm.CloseConvReq, callOptions ...callopt.Option) (r *pm.CloseConvResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseConv(ctx, req)
}
