// Code generated by Kitex v0.16.1. DO NOT EDIT.

package feedservice

import (
	"context"
	feed "eigenflux_server/kitex_gen/eigenflux/feed"
	sort "eigenflux_server/kitex_gen/eigenflux/sort"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Discovery(ctx context.Context, req *sort.DiscoveryReq, callOptions ...callopt.Option) (r *sort.DiscoveryResp, err error)
	FetchFeed(ctx context.Context, req *feed.FetchFeedReq, callOptions ...callopt.Option) (r *feed.FetchFeedResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFeedServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFeedServiceClient struct {
	*kClient
}

func (p *kFeedServiceClient) Discovery(ctx context.Context, req *sort.DiscoveryReq, callOptions ...callopt.Option) (r *sort.DiscoveryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Discovery(ctx, req)
}

func (p *kFeedServiceClient) FetchFeed(ctx context.Context, req *feed.FetchFeedReq, callOptions ...callopt.Option) (r *feed.FetchFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchFeed(ctx, req)
}
