// Code generated by Kitex v0.16.1. DO NOT EDIT.

package orderservice

import (
	"context"
	order "eigenflux_server/kitex_gen/eigenflux/order"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetCommissionStatistics(ctx context.Context, req *order.GetCommissionStatisticsReq, callOptions ...callopt.Option) (r *order.GetCommissionStatisticsResp, err error)
	BatchGetCommissionStatistics(ctx context.Context, req *order.BatchGetCommissionStatisticsReq, callOptions ...callopt.Option) (r *order.BatchGetCommissionStatisticsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) GetCommissionStatistics(ctx context.Context, req *order.GetCommissionStatisticsReq, callOptions ...callopt.Option) (r *order.GetCommissionStatisticsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommissionStatistics(ctx, req)
}

func (p *kOrderServiceClient) BatchGetCommissionStatistics(ctx context.Context, req *order.BatchGetCommissionStatisticsReq, callOptions ...callopt.Option) (r *order.BatchGetCommissionStatisticsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetCommissionStatistics(ctx, req)
}
