// Code generated by Kitex v0.16.1. DO NOT EDIT.

package orderservice

import (
	"context"
	order "eigenflux_server/kitex_gen/eigenflux/order"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetCommissionStatistics": kitex.NewMethodInfo(
		getCommissionStatisticsHandler,
		newOrderServiceGetCommissionStatisticsArgs,
		newOrderServiceGetCommissionStatisticsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetCommissionStatistics": kitex.NewMethodInfo(
		batchGetCommissionStatisticsHandler,
		newOrderServiceBatchGetCommissionStatisticsArgs,
		newOrderServiceBatchGetCommissionStatisticsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*order.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getCommissionStatisticsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceGetCommissionStatisticsArgs)
	realResult := result.(*order.OrderServiceGetCommissionStatisticsResult)
	success, err := handler.(order.OrderService).GetCommissionStatistics(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetCommissionStatisticsArgs() interface{} {
	return order.NewOrderServiceGetCommissionStatisticsArgs()
}

func newOrderServiceGetCommissionStatisticsResult() interface{} {
	return order.NewOrderServiceGetCommissionStatisticsResult()
}

func batchGetCommissionStatisticsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceBatchGetCommissionStatisticsArgs)
	realResult := result.(*order.OrderServiceBatchGetCommissionStatisticsResult)
	success, err := handler.(order.OrderService).BatchGetCommissionStatistics(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceBatchGetCommissionStatisticsArgs() interface{} {
	return order.NewOrderServiceBatchGetCommissionStatisticsArgs()
}

func newOrderServiceBatchGetCommissionStatisticsResult() interface{} {
	return order.NewOrderServiceBatchGetCommissionStatisticsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetCommissionStatistics(ctx context.Context, req *order.GetCommissionStatisticsReq) (r *order.GetCommissionStatisticsResp, err error) {
	var _args order.OrderServiceGetCommissionStatisticsArgs
	_args.Req = req
	var _result order.OrderServiceGetCommissionStatisticsResult
	if err = p.c.Call(ctx, "GetCommissionStatistics", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetCommissionStatistics(ctx context.Context, req *order.BatchGetCommissionStatisticsReq) (r *order.BatchGetCommissionStatisticsResp, err error) {
	var _args order.OrderServiceBatchGetCommissionStatisticsArgs
	_args.Req = req
	var _result order.OrderServiceBatchGetCommissionStatisticsResult
	if err = p.c.Call(ctx, "BatchGetCommissionStatistics", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
