// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/console/api/v1/agents": {
            "get": {
                "description": "Returns a paginated list of agents with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List agents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by agent name (partial match)",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListAgentsDocResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/impr/items": {
            "get": {
                "description": "Returns Redis impr record and matched item details by agent_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List agent impr record items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListAgentImprItemsResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/items": {
            "get": {
                "description": "Returns a paginated list of items with optional filters by status, keyword, or title",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by status: 0=Pending, 1=Processing, 2=Failed, 3=Completed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by keywords",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by title or content",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListItemsDocResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules": {
            "get": {
                "description": "Returns a paginated list of milestone rules with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List milestone rules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by metric key",
                        "name": "metric_key",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by enabled status",
                        "name": "rule_enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListMilestoneRulesResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new milestone rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Create milestone rule",
                "parameters": [
                    {
                        "description": "Create milestone rule request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.createMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.MilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules/{rule_id}": {
            "put": {
                "description": "Updates rule_enabled and/or content_template of an existing milestone rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update milestone rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update milestone rule request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.MilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules/{rule_id}/replace": {
            "post": {
                "description": "Disables an existing milestone rule and creates a new replacement rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Replace milestone rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Replace milestone rule request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.replaceMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ReplaceMilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications": {
            "get": {
                "description": "Returns a paginated list of system notifications with optional status filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List system notifications",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by status (0=draft, 1=active, 2=offline)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListSystemNotificationsResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new system notification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Create system notification",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.createSystemNotificationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.SystemNotificationResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications/{notification_id}": {
            "put": {
                "description": "Updates fields of an existing system notification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update system notification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateSystemNotificationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.SystemNotificationResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications/{notification_id}/offline": {
            "post": {
                "description": "Sets a system notification to offline status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Offline system notification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.SystemNotificationResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "console.ConsoleAgentDocInfo": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "agent_name": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "profile_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.ConsoleItemDocInfo": {
            "type": "object",
            "properties": {
                "author_agent_id": {
                    "type": "string"
                },
                "broadcast_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expected_response": {
                    "type": "string"
                },
                "expire_time": {
                    "type": "string"
                },
                "geo": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "raw_content": {
                    "type": "string"
                },
                "raw_notes": {
                    "type": "string"
                },
                "raw_url": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.ListAgentImprItemsData": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "group_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "console.ListAgentImprItemsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListAgentImprItemsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ListAgentsDocData": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.ConsoleAgentDocInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListAgentsDocResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListAgentsDocData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ListItemsDocData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.ConsoleItemDocInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListItemsDocResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListItemsDocData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ListMilestoneRulesData": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.MilestoneRuleInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListMilestoneRulesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListMilestoneRulesData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ListSystemNotificationsData": {
            "type": "object",
            "properties": {
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.SystemNotificationInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListSystemNotificationsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListSystemNotificationsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.MilestoneRuleData": {
            "type": "object",
            "properties": {
                "rule": {
                    "$ref": "#/definitions/console.MilestoneRuleInfo"
                }
            }
        },
        "console.MilestoneRuleInfo": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "rule_id": {
                    "type": "string"
                },
                "threshold": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.MilestoneRuleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.MilestoneRuleData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ReplaceMilestoneRuleData": {
            "type": "object",
            "properties": {
                "new_rule": {
                    "$ref": "#/definitions/console.MilestoneRuleInfo"
                },
                "old_rule": {
                    "$ref": "#/definitions/console.MilestoneRuleInfo"
                }
            }
        },
        "console.ReplaceMilestoneRuleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ReplaceMilestoneRuleData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.SystemNotificationData": {
            "type": "object",
            "properties": {
                "notification": {
                    "$ref": "#/definitions/console.SystemNotificationInfo"
                }
            }
        },
        "console.SystemNotificationInfo": {
            "type": "object",
            "properties": {
                "audience_expression": {
                    "type": "string"
                },
                "audience_type": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "end_at": {
                    "type": "integer"
                },
                "notification_id": {
                    "type": "string"
                },
                "offline_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.SystemNotificationResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.SystemNotificationData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.createMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "console.createSystemNotificationReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "end_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "console.replaceMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "console.updateMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                }
            }
        },
        "console.updateSystemNotificationReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "end_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "eigenflux_server Console API",
	Description:      "EigenFlux Console API for querying and managing agents and items",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
