// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package trade

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type TradingService struct {
	ServiceId          int64    `thrift:"service_id,1" frugal:"1,default,i64" json:"service_id"`
	SellerAgentId      int64    `thrift:"seller_agent_id,2" frugal:"2,default,i64" json:"seller_agent_id"`
	Title              string   `thrift:"title,3" frugal:"3,default,string" json:"title"`
	CapabilityDesc     string   `thrift:"capability_desc,4" frugal:"4,default,string" json:"capability_desc"`
	CallSpecText       string   `thrift:"call_spec_text,5" frugal:"5,default,string" json:"call_spec_text"`
	CallSpecSchema     string   `thrift:"call_spec_schema,6" frugal:"6,default,string" json:"call_spec_schema"`
	PriceText          string   `thrift:"price_text,7" frugal:"7,default,string" json:"price_text"`
	AmountAtomic       int64    `thrift:"amount_atomic,8" frugal:"8,default,i64" json:"amount_atomic"`
	Asset              string   `thrift:"asset,9" frugal:"9,default,string" json:"asset"`
	DeliveryDeadlineMs int64    `thrift:"delivery_deadline_ms,10" frugal:"10,default,i64" json:"delivery_deadline_ms"`
	Status             int16    `thrift:"status,11" frugal:"11,default,i16" json:"status"`
	SuccessRate        float64  `thrift:"success_rate,12" frugal:"12,default,double" json:"success_rate"`
	AvgLatencyMs       int64    `thrift:"avg_latency_ms,13" frugal:"13,default,i64" json:"avg_latency_ms"`
	OrderCount         int32    `thrift:"order_count,14" frugal:"14,default,i32" json:"order_count"`
	ReleasedCount      int32    `thrift:"released_count,15" frugal:"15,default,i32" json:"released_count"`
	RefundedCount      int32    `thrift:"refunded_count,16" frugal:"16,default,i32" json:"refunded_count"`
	ExpiredCount       int32    `thrift:"expired_count,17" frugal:"17,default,i32" json:"expired_count"`
	CreatedAt          int64    `thrift:"created_at,18" frugal:"18,default,i64" json:"created_at"`
	UpdatedAt          int64    `thrift:"updated_at,19" frugal:"19,default,i64" json:"updated_at"`
	CapabilityTags     []string `thrift:"capability_tags,20" frugal:"20,default,list<string>" json:"capability_tags"`
	UseCases           string   `thrift:"use_cases,21" frugal:"21,default,string" json:"use_cases"`
	EnrichmentVersion  int32    `thrift:"enrichment_version,22" frugal:"22,default,i32" json:"enrichment_version"`
}

func NewTradingService() *TradingService {
	return &TradingService{}
}

func (p *TradingService) InitDefault() {
}

func (p *TradingService) GetServiceId() (v int64) {
	return p.ServiceId
}

func (p *TradingService) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *TradingService) GetTitle() (v string) {
	return p.Title
}

func (p *TradingService) GetCapabilityDesc() (v string) {
	return p.CapabilityDesc
}

func (p *TradingService) GetCallSpecText() (v string) {
	return p.CallSpecText
}

func (p *TradingService) GetCallSpecSchema() (v string) {
	return p.CallSpecSchema
}

func (p *TradingService) GetPriceText() (v string) {
	return p.PriceText
}

func (p *TradingService) GetAmountAtomic() (v int64) {
	return p.AmountAtomic
}

func (p *TradingService) GetAsset() (v string) {
	return p.Asset
}

func (p *TradingService) GetDeliveryDeadlineMs() (v int64) {
	return p.DeliveryDeadlineMs
}

func (p *TradingService) GetStatus() (v int16) {
	return p.Status
}

func (p *TradingService) GetSuccessRate() (v float64) {
	return p.SuccessRate
}

func (p *TradingService) GetAvgLatencyMs() (v int64) {
	return p.AvgLatencyMs
}

func (p *TradingService) GetOrderCount() (v int32) {
	return p.OrderCount
}

func (p *TradingService) GetReleasedCount() (v int32) {
	return p.ReleasedCount
}

func (p *TradingService) GetRefundedCount() (v int32) {
	return p.RefundedCount
}

func (p *TradingService) GetExpiredCount() (v int32) {
	return p.ExpiredCount
}

func (p *TradingService) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *TradingService) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *TradingService) GetCapabilityTags() (v []string) {
	return p.CapabilityTags
}

func (p *TradingService) GetUseCases() (v string) {
	return p.UseCases
}

func (p *TradingService) GetEnrichmentVersion() (v int32) {
	return p.EnrichmentVersion
}
func (p *TradingService) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *TradingService) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *TradingService) SetTitle(val string) {
	p.Title = val
}
func (p *TradingService) SetCapabilityDesc(val string) {
	p.CapabilityDesc = val
}
func (p *TradingService) SetCallSpecText(val string) {
	p.CallSpecText = val
}
func (p *TradingService) SetCallSpecSchema(val string) {
	p.CallSpecSchema = val
}
func (p *TradingService) SetPriceText(val string) {
	p.PriceText = val
}
func (p *TradingService) SetAmountAtomic(val int64) {
	p.AmountAtomic = val
}
func (p *TradingService) SetAsset(val string) {
	p.Asset = val
}
func (p *TradingService) SetDeliveryDeadlineMs(val int64) {
	p.DeliveryDeadlineMs = val
}
func (p *TradingService) SetStatus(val int16) {
	p.Status = val
}
func (p *TradingService) SetSuccessRate(val float64) {
	p.SuccessRate = val
}
func (p *TradingService) SetAvgLatencyMs(val int64) {
	p.AvgLatencyMs = val
}
func (p *TradingService) SetOrderCount(val int32) {
	p.OrderCount = val
}
func (p *TradingService) SetReleasedCount(val int32) {
	p.ReleasedCount = val
}
func (p *TradingService) SetRefundedCount(val int32) {
	p.RefundedCount = val
}
func (p *TradingService) SetExpiredCount(val int32) {
	p.ExpiredCount = val
}
func (p *TradingService) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *TradingService) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *TradingService) SetCapabilityTags(val []string) {
	p.CapabilityTags = val
}
func (p *TradingService) SetUseCases(val string) {
	p.UseCases = val
}
func (p *TradingService) SetEnrichmentVersion(val int32) {
	p.EnrichmentVersion = val
}

func (p *TradingService) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradingService(%+v)", *p)
}

var fieldIDToName_TradingService = map[int16]string{
	1:  "service_id",
	2:  "seller_agent_id",
	3:  "title",
	4:  "capability_desc",
	5:  "call_spec_text",
	6:  "call_spec_schema",
	7:  "price_text",
	8:  "amount_atomic",
	9:  "asset",
	10: "delivery_deadline_ms",
	11: "status",
	12: "success_rate",
	13: "avg_latency_ms",
	14: "order_count",
	15: "released_count",
	16: "refunded_count",
	17: "expired_count",
	18: "created_at",
	19: "updated_at",
	20: "capability_tags",
	21: "use_cases",
	22: "enrichment_version",
}

type TradeOrder struct {
	OrderId                  int64  `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	ServiceId                int64  `thrift:"service_id,2" frugal:"2,default,i64" json:"service_id"`
	BuyerAgentId             int64  `thrift:"buyer_agent_id,3" frugal:"3,default,i64" json:"buyer_agent_id"`
	SellerAgentId            int64  `thrift:"seller_agent_id,4" frugal:"4,default,i64" json:"seller_agent_id"`
	Status                   int16  `thrift:"status,5" frugal:"5,default,i16" json:"status"`
	TransferId               string `thrift:"transfer_id,6" frugal:"6,default,string" json:"transfer_id"`
	TransferState            string `thrift:"transfer_state,7" frugal:"7,default,string" json:"transfer_state"`
	FrozenTitle              string `thrift:"frozen_title,8" frugal:"8,default,string" json:"frozen_title"`
	FrozenCallSpecText       string `thrift:"frozen_call_spec_text,9" frugal:"9,default,string" json:"frozen_call_spec_text"`
	FrozenCallSpecSchema     string `thrift:"frozen_call_spec_schema,10" frugal:"10,default,string" json:"frozen_call_spec_schema"`
	FrozenAmountAtomic       int64  `thrift:"frozen_amount_atomic,11" frugal:"11,default,i64" json:"frozen_amount_atomic"`
	FrozenAsset              string `thrift:"frozen_asset,12" frugal:"12,default,string" json:"frozen_asset"`
	FrozenDeliveryDeadlineMs int64  `thrift:"frozen_delivery_deadline_ms,13" frugal:"13,default,i64" json:"frozen_delivery_deadline_ms"`
	BuyerInput               string `thrift:"buyer_input,14" frugal:"14,default,string" json:"buyer_input"`
	DeliveryPayload          string `thrift:"delivery_payload,15" frugal:"15,default,string" json:"delivery_payload"`
	CreatedAt                int64  `thrift:"created_at,16" frugal:"16,default,i64" json:"created_at"`
	DeadlineAt               int64  `thrift:"deadline_at,17" frugal:"17,default,i64" json:"deadline_at"`
	PaidAt                   int64  `thrift:"paid_at,18" frugal:"18,default,i64" json:"paid_at"`
	DeliveredAt              int64  `thrift:"delivered_at,19" frugal:"19,default,i64" json:"delivered_at"`
	ReleasedAt               int64  `thrift:"released_at,20" frugal:"20,default,i64" json:"released_at"`
	RefundedAt               int64  `thrift:"refunded_at,21" frugal:"21,default,i64" json:"refunded_at"`
	ClosedAt                 int64  `thrift:"closed_at,22" frugal:"22,default,i64" json:"closed_at"`
}

func NewTradeOrder() *TradeOrder {
	return &TradeOrder{}
}

func (p *TradeOrder) InitDefault() {
}

func (p *TradeOrder) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *TradeOrder) GetServiceId() (v int64) {
	return p.ServiceId
}

func (p *TradeOrder) GetBuyerAgentId() (v int64) {
	return p.BuyerAgentId
}

func (p *TradeOrder) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *TradeOrder) GetStatus() (v int16) {
	return p.Status
}

func (p *TradeOrder) GetTransferId() (v string) {
	return p.TransferId
}

func (p *TradeOrder) GetTransferState() (v string) {
	return p.TransferState
}

func (p *TradeOrder) GetFrozenTitle() (v string) {
	return p.FrozenTitle
}

func (p *TradeOrder) GetFrozenCallSpecText() (v string) {
	return p.FrozenCallSpecText
}

func (p *TradeOrder) GetFrozenCallSpecSchema() (v string) {
	return p.FrozenCallSpecSchema
}

func (p *TradeOrder) GetFrozenAmountAtomic() (v int64) {
	return p.FrozenAmountAtomic
}

func (p *TradeOrder) GetFrozenAsset() (v string) {
	return p.FrozenAsset
}

func (p *TradeOrder) GetFrozenDeliveryDeadlineMs() (v int64) {
	return p.FrozenDeliveryDeadlineMs
}

func (p *TradeOrder) GetBuyerInput() (v string) {
	return p.BuyerInput
}

func (p *TradeOrder) GetDeliveryPayload() (v string) {
	return p.DeliveryPayload
}

func (p *TradeOrder) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *TradeOrder) GetDeadlineAt() (v int64) {
	return p.DeadlineAt
}

func (p *TradeOrder) GetPaidAt() (v int64) {
	return p.PaidAt
}

func (p *TradeOrder) GetDeliveredAt() (v int64) {
	return p.DeliveredAt
}

func (p *TradeOrder) GetReleasedAt() (v int64) {
	return p.ReleasedAt
}

func (p *TradeOrder) GetRefundedAt() (v int64) {
	return p.RefundedAt
}

func (p *TradeOrder) GetClosedAt() (v int64) {
	return p.ClosedAt
}
func (p *TradeOrder) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *TradeOrder) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *TradeOrder) SetBuyerAgentId(val int64) {
	p.BuyerAgentId = val
}
func (p *TradeOrder) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *TradeOrder) SetStatus(val int16) {
	p.Status = val
}
func (p *TradeOrder) SetTransferId(val string) {
	p.TransferId = val
}
func (p *TradeOrder) SetTransferState(val string) {
	p.TransferState = val
}
func (p *TradeOrder) SetFrozenTitle(val string) {
	p.FrozenTitle = val
}
func (p *TradeOrder) SetFrozenCallSpecText(val string) {
	p.FrozenCallSpecText = val
}
func (p *TradeOrder) SetFrozenCallSpecSchema(val string) {
	p.FrozenCallSpecSchema = val
}
func (p *TradeOrder) SetFrozenAmountAtomic(val int64) {
	p.FrozenAmountAtomic = val
}
func (p *TradeOrder) SetFrozenAsset(val string) {
	p.FrozenAsset = val
}
func (p *TradeOrder) SetFrozenDeliveryDeadlineMs(val int64) {
	p.FrozenDeliveryDeadlineMs = val
}
func (p *TradeOrder) SetBuyerInput(val string) {
	p.BuyerInput = val
}
func (p *TradeOrder) SetDeliveryPayload(val string) {
	p.DeliveryPayload = val
}
func (p *TradeOrder) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *TradeOrder) SetDeadlineAt(val int64) {
	p.DeadlineAt = val
}
func (p *TradeOrder) SetPaidAt(val int64) {
	p.PaidAt = val
}
func (p *TradeOrder) SetDeliveredAt(val int64) {
	p.DeliveredAt = val
}
func (p *TradeOrder) SetReleasedAt(val int64) {
	p.ReleasedAt = val
}
func (p *TradeOrder) SetRefundedAt(val int64) {
	p.RefundedAt = val
}
func (p *TradeOrder) SetClosedAt(val int64) {
	p.ClosedAt = val
}

func (p *TradeOrder) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeOrder(%+v)", *p)
}

var fieldIDToName_TradeOrder = map[int16]string{
	1:  "order_id",
	2:  "service_id",
	3:  "buyer_agent_id",
	4:  "seller_agent_id",
	5:  "status",
	6:  "transfer_id",
	7:  "transfer_state",
	8:  "frozen_title",
	9:  "frozen_call_spec_text",
	10: "frozen_call_spec_schema",
	11: "frozen_amount_atomic",
	12: "frozen_asset",
	13: "frozen_delivery_deadline_ms",
	14: "buyer_input",
	15: "delivery_payload",
	16: "created_at",
	17: "deadline_at",
	18: "paid_at",
	19: "delivered_at",
	20: "released_at",
	21: "refunded_at",
	22: "closed_at",
}

type TradeOrderEvent struct {
	EventId      int64  `thrift:"event_id,1" frugal:"1,default,i64" json:"event_id"`
	OrderId      int64  `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	EventType    string `thrift:"event_type,3" frugal:"3,default,string" json:"event_type"`
	ActorAgentId int64  `thrift:"actor_agent_id,4" frugal:"4,default,i64" json:"actor_agent_id"`
	PayloadJson  string `thrift:"payload_json,5" frugal:"5,default,string" json:"payload_json"`
	CreatedAt    int64  `thrift:"created_at,6" frugal:"6,default,i64" json:"created_at"`
}

func NewTradeOrderEvent() *TradeOrderEvent {
	return &TradeOrderEvent{}
}

func (p *TradeOrderEvent) InitDefault() {
}

func (p *TradeOrderEvent) GetEventId() (v int64) {
	return p.EventId
}

func (p *TradeOrderEvent) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *TradeOrderEvent) GetEventType() (v string) {
	return p.EventType
}

func (p *TradeOrderEvent) GetActorAgentId() (v int64) {
	return p.ActorAgentId
}

func (p *TradeOrderEvent) GetPayloadJson() (v string) {
	return p.PayloadJson
}

func (p *TradeOrderEvent) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *TradeOrderEvent) SetEventId(val int64) {
	p.EventId = val
}
func (p *TradeOrderEvent) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *TradeOrderEvent) SetEventType(val string) {
	p.EventType = val
}
func (p *TradeOrderEvent) SetActorAgentId(val int64) {
	p.ActorAgentId = val
}
func (p *TradeOrderEvent) SetPayloadJson(val string) {
	p.PayloadJson = val
}
func (p *TradeOrderEvent) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *TradeOrderEvent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeOrderEvent(%+v)", *p)
}

var fieldIDToName_TradeOrderEvent = map[int16]string{
	1: "event_id",
	2: "order_id",
	3: "event_type",
	4: "actor_agent_id",
	5: "payload_json",
	6: "created_at",
}

type PublishServiceReq struct {
	SellerAgentId      int64  `thrift:"seller_agent_id,1" frugal:"1,default,i64" json:"seller_agent_id"`
	Title              string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	CapabilityDesc     string `thrift:"capability_desc,3" frugal:"3,default,string" json:"capability_desc"`
	CallSpecText       string `thrift:"call_spec_text,4" frugal:"4,default,string" json:"call_spec_text"`
	CallSpecSchema     string `thrift:"call_spec_schema,5" frugal:"5,default,string" json:"call_spec_schema"`
	PriceText          string `thrift:"price_text,6" frugal:"6,default,string" json:"price_text"`
	AmountAtomic       int64  `thrift:"amount_atomic,7" frugal:"7,default,i64" json:"amount_atomic"`
	Asset              string `thrift:"asset,8" frugal:"8,default,string" json:"asset"`
	DeliveryDeadlineMs int64  `thrift:"delivery_deadline_ms,9" frugal:"9,default,i64" json:"delivery_deadline_ms"`
}

func NewPublishServiceReq() *PublishServiceReq {
	return &PublishServiceReq{}
}

func (p *PublishServiceReq) InitDefault() {
}

func (p *PublishServiceReq) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *PublishServiceReq) GetTitle() (v string) {
	return p.Title
}

func (p *PublishServiceReq) GetCapabilityDesc() (v string) {
	return p.CapabilityDesc
}

func (p *PublishServiceReq) GetCallSpecText() (v string) {
	return p.CallSpecText
}

func (p *PublishServiceReq) GetCallSpecSchema() (v string) {
	return p.CallSpecSchema
}

func (p *PublishServiceReq) GetPriceText() (v string) {
	return p.PriceText
}

func (p *PublishServiceReq) GetAmountAtomic() (v int64) {
	return p.AmountAtomic
}

func (p *PublishServiceReq) GetAsset() (v string) {
	return p.Asset
}

func (p *PublishServiceReq) GetDeliveryDeadlineMs() (v int64) {
	return p.DeliveryDeadlineMs
}
func (p *PublishServiceReq) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *PublishServiceReq) SetTitle(val string) {
	p.Title = val
}
func (p *PublishServiceReq) SetCapabilityDesc(val string) {
	p.CapabilityDesc = val
}
func (p *PublishServiceReq) SetCallSpecText(val string) {
	p.CallSpecText = val
}
func (p *PublishServiceReq) SetCallSpecSchema(val string) {
	p.CallSpecSchema = val
}
func (p *PublishServiceReq) SetPriceText(val string) {
	p.PriceText = val
}
func (p *PublishServiceReq) SetAmountAtomic(val int64) {
	p.AmountAtomic = val
}
func (p *PublishServiceReq) SetAsset(val string) {
	p.Asset = val
}
func (p *PublishServiceReq) SetDeliveryDeadlineMs(val int64) {
	p.DeliveryDeadlineMs = val
}

func (p *PublishServiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishServiceReq(%+v)", *p)
}

var fieldIDToName_PublishServiceReq = map[int16]string{
	1: "seller_agent_id",
	2: "title",
	3: "capability_desc",
	4: "call_spec_text",
	5: "call_spec_schema",
	6: "price_text",
	7: "amount_atomic",
	8: "asset",
	9: "delivery_deadline_ms",
}

type PublishServiceResp struct {
	ServiceId int64          `thrift:"service_id,1" frugal:"1,default,i64" json:"service_id"`
	BaseResp  *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewPublishServiceResp() *PublishServiceResp {
	return &PublishServiceResp{}
}

func (p *PublishServiceResp) InitDefault() {
}

func (p *PublishServiceResp) GetServiceId() (v int64) {
	return p.ServiceId
}

var PublishServiceResp_BaseResp_DEFAULT *base.BaseResp

func (p *PublishServiceResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return PublishServiceResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *PublishServiceResp) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *PublishServiceResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *PublishServiceResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PublishServiceResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishServiceResp(%+v)", *p)
}

var fieldIDToName_PublishServiceResp = map[int16]string{
	1:   "service_id",
	255: "base_resp",
}

type UpdateServiceReq struct {
	ServiceId          int64  `thrift:"service_id,1" frugal:"1,default,i64" json:"service_id"`
	SellerAgentId      int64  `thrift:"seller_agent_id,2" frugal:"2,default,i64" json:"seller_agent_id"`
	Title              string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	CapabilityDesc     string `thrift:"capability_desc,4" frugal:"4,default,string" json:"capability_desc"`
	CallSpecText       string `thrift:"call_spec_text,5" frugal:"5,default,string" json:"call_spec_text"`
	CallSpecSchema     string `thrift:"call_spec_schema,6" frugal:"6,default,string" json:"call_spec_schema"`
	PriceText          string `thrift:"price_text,7" frugal:"7,default,string" json:"price_text"`
	AmountAtomic       int64  `thrift:"amount_atomic,8" frugal:"8,default,i64" json:"amount_atomic"`
	Asset              string `thrift:"asset,9" frugal:"9,default,string" json:"asset"`
	DeliveryDeadlineMs int64  `thrift:"delivery_deadline_ms,10" frugal:"10,default,i64" json:"delivery_deadline_ms"`
}

func NewUpdateServiceReq() *UpdateServiceReq {
	return &UpdateServiceReq{}
}

func (p *UpdateServiceReq) InitDefault() {
}

func (p *UpdateServiceReq) GetServiceId() (v int64) {
	return p.ServiceId
}

func (p *UpdateServiceReq) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *UpdateServiceReq) GetTitle() (v string) {
	return p.Title
}

func (p *UpdateServiceReq) GetCapabilityDesc() (v string) {
	return p.CapabilityDesc
}

func (p *UpdateServiceReq) GetCallSpecText() (v string) {
	return p.CallSpecText
}

func (p *UpdateServiceReq) GetCallSpecSchema() (v string) {
	return p.CallSpecSchema
}

func (p *UpdateServiceReq) GetPriceText() (v string) {
	return p.PriceText
}

func (p *UpdateServiceReq) GetAmountAtomic() (v int64) {
	return p.AmountAtomic
}

func (p *UpdateServiceReq) GetAsset() (v string) {
	return p.Asset
}

func (p *UpdateServiceReq) GetDeliveryDeadlineMs() (v int64) {
	return p.DeliveryDeadlineMs
}
func (p *UpdateServiceReq) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *UpdateServiceReq) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *UpdateServiceReq) SetTitle(val string) {
	p.Title = val
}
func (p *UpdateServiceReq) SetCapabilityDesc(val string) {
	p.CapabilityDesc = val
}
func (p *UpdateServiceReq) SetCallSpecText(val string) {
	p.CallSpecText = val
}
func (p *UpdateServiceReq) SetCallSpecSchema(val string) {
	p.CallSpecSchema = val
}
func (p *UpdateServiceReq) SetPriceText(val string) {
	p.PriceText = val
}
func (p *UpdateServiceReq) SetAmountAtomic(val int64) {
	p.AmountAtomic = val
}
func (p *UpdateServiceReq) SetAsset(val string) {
	p.Asset = val
}
func (p *UpdateServiceReq) SetDeliveryDeadlineMs(val int64) {
	p.DeliveryDeadlineMs = val
}

func (p *UpdateServiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateServiceReq(%+v)", *p)
}

var fieldIDToName_UpdateServiceReq = map[int16]string{
	1:  "service_id",
	2:  "seller_agent_id",
	3:  "title",
	4:  "capability_desc",
	5:  "call_spec_text",
	6:  "call_spec_schema",
	7:  "price_text",
	8:  "amount_atomic",
	9:  "asset",
	10: "delivery_deadline_ms",
}

type UpdateServiceResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewUpdateServiceResp() *UpdateServiceResp {
	return &UpdateServiceResp{}
}

func (p *UpdateServiceResp) InitDefault() {
}

var UpdateServiceResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateServiceResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateServiceResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateServiceResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateServiceResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateServiceResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateServiceResp(%+v)", *p)
}

var fieldIDToName_UpdateServiceResp = map[int16]string{
	255: "base_resp",
}

type OfflineServiceReq struct {
	ServiceId     int64 `thrift:"service_id,1" frugal:"1,default,i64" json:"service_id"`
	SellerAgentId int64 `thrift:"seller_agent_id,2" frugal:"2,default,i64" json:"seller_agent_id"`
}

func NewOfflineServiceReq() *OfflineServiceReq {
	return &OfflineServiceReq{}
}

func (p *OfflineServiceReq) InitDefault() {
}

func (p *OfflineServiceReq) GetServiceId() (v int64) {
	return p.ServiceId
}

func (p *OfflineServiceReq) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}
func (p *OfflineServiceReq) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *OfflineServiceReq) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}

func (p *OfflineServiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OfflineServiceReq(%+v)", *p)
}

var fieldIDToName_OfflineServiceReq = map[int16]string{
	1: "service_id",
	2: "seller_agent_id",
}

type OfflineServiceResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewOfflineServiceResp() *OfflineServiceResp {
	return &OfflineServiceResp{}
}

func (p *OfflineServiceResp) InitDefault() {
}

var OfflineServiceResp_BaseResp_DEFAULT *base.BaseResp

func (p *OfflineServiceResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return OfflineServiceResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *OfflineServiceResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *OfflineServiceResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *OfflineServiceResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OfflineServiceResp(%+v)", *p)
}

var fieldIDToName_OfflineServiceResp = map[int16]string{
	255: "base_resp",
}

type GetMyServicesReq struct {
	SellerAgentId int64  `thrift:"seller_agent_id,1" frugal:"1,default,i64" json:"seller_agent_id"`
	Limit         int32  `thrift:"limit,2" frugal:"2,default,i32" json:"limit"`
	Cursor        string `thrift:"cursor,3" frugal:"3,default,string" json:"cursor"`
}

func NewGetMyServicesReq() *GetMyServicesReq {
	return &GetMyServicesReq{}
}

func (p *GetMyServicesReq) InitDefault() {
}

func (p *GetMyServicesReq) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *GetMyServicesReq) GetLimit() (v int32) {
	return p.Limit
}

func (p *GetMyServicesReq) GetCursor() (v string) {
	return p.Cursor
}
func (p *GetMyServicesReq) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *GetMyServicesReq) SetLimit(val int32) {
	p.Limit = val
}
func (p *GetMyServicesReq) SetCursor(val string) {
	p.Cursor = val
}

func (p *GetMyServicesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMyServicesReq(%+v)", *p)
}

var fieldIDToName_GetMyServicesReq = map[int16]string{
	1: "seller_agent_id",
	2: "limit",
	3: "cursor",
}

type GetMyServicesResp struct {
	Services   []*TradingService `thrift:"services,1" frugal:"1,default,list<TradingService>" json:"services"`
	NextCursor string            `thrift:"next_cursor,2" frugal:"2,default,string" json:"next_cursor"`
	BaseResp   *base.BaseResp    `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetMyServicesResp() *GetMyServicesResp {
	return &GetMyServicesResp{}
}

func (p *GetMyServicesResp) InitDefault() {
}

func (p *GetMyServicesResp) GetServices() (v []*TradingService) {
	return p.Services
}

func (p *GetMyServicesResp) GetNextCursor() (v string) {
	return p.NextCursor
}

var GetMyServicesResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetMyServicesResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetMyServicesResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetMyServicesResp) SetServices(val []*TradingService) {
	p.Services = val
}
func (p *GetMyServicesResp) SetNextCursor(val string) {
	p.NextCursor = val
}
func (p *GetMyServicesResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetMyServicesResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetMyServicesResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMyServicesResp(%+v)", *p)
}

var fieldIDToName_GetMyServicesResp = map[int16]string{
	1:   "services",
	2:   "next_cursor",
	255: "base_resp",
}

type CreateOrderReq struct {
	BuyerAgentId   int64  `thrift:"buyer_agent_id,1" frugal:"1,default,i64" json:"buyer_agent_id"`
	ServiceId      int64  `thrift:"service_id,2" frugal:"2,default,i64" json:"service_id"`
	BuyerInput     string `thrift:"buyer_input,3" frugal:"3,default,string" json:"buyer_input"`
	IdempotencyKey string `thrift:"idempotency_key,4" frugal:"4,default,string" json:"idempotency_key"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetBuyerAgentId() (v int64) {
	return p.BuyerAgentId
}

func (p *CreateOrderReq) GetServiceId() (v int64) {
	return p.ServiceId
}

func (p *CreateOrderReq) GetBuyerInput() (v string) {
	return p.BuyerInput
}

func (p *CreateOrderReq) GetIdempotencyKey() (v string) {
	return p.IdempotencyKey
}
func (p *CreateOrderReq) SetBuyerAgentId(val int64) {
	p.BuyerAgentId = val
}
func (p *CreateOrderReq) SetServiceId(val int64) {
	p.ServiceId = val
}
func (p *CreateOrderReq) SetBuyerInput(val string) {
	p.BuyerInput = val
}
func (p *CreateOrderReq) SetIdempotencyKey(val string) {
	p.IdempotencyKey = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "buyer_agent_id",
	2: "service_id",
	3: "buyer_input",
	4: "idempotency_key",
}

type CreateOrderResp struct {
	OrderId  int64          `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (p *CreateOrderResp) InitDefault() {
}

func (p *CreateOrderResp) GetOrderId() (v int64) {
	return p.OrderId
}

var CreateOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateOrderResp) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CreateOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1:   "order_id",
	255: "base_resp",
}

type DeliverOrderReq struct {
	OrderId         int64  `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	SellerAgentId   int64  `thrift:"seller_agent_id,2" frugal:"2,default,i64" json:"seller_agent_id"`
	DeliveryPayload string `thrift:"delivery_payload,3" frugal:"3,default,string" json:"delivery_payload"`
}

func NewDeliverOrderReq() *DeliverOrderReq {
	return &DeliverOrderReq{}
}

func (p *DeliverOrderReq) InitDefault() {
}

func (p *DeliverOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *DeliverOrderReq) GetSellerAgentId() (v int64) {
	return p.SellerAgentId
}

func (p *DeliverOrderReq) GetDeliveryPayload() (v string) {
	return p.DeliveryPayload
}
func (p *DeliverOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *DeliverOrderReq) SetSellerAgentId(val int64) {
	p.SellerAgentId = val
}
func (p *DeliverOrderReq) SetDeliveryPayload(val string) {
	p.DeliveryPayload = val
}

func (p *DeliverOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeliverOrderReq(%+v)", *p)
}

var fieldIDToName_DeliverOrderReq = map[int16]string{
	1: "order_id",
	2: "seller_agent_id",
	3: "delivery_payload",
}

type DeliverOrderResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewDeliverOrderResp() *DeliverOrderResp {
	return &DeliverOrderResp{}
}

func (p *DeliverOrderResp) InitDefault() {
}

var DeliverOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *DeliverOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeliverOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeliverOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeliverOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeliverOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeliverOrderResp(%+v)", *p)
}

var fieldIDToName_DeliverOrderResp = map[int16]string{
	255: "base_resp",
}

type ReleaseOrderReq struct {
	OrderId      int64  `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	BuyerAgentId int64  `thrift:"buyer_agent_id,2" frugal:"2,default,i64" json:"buyer_agent_id"`
	TransferId   string `thrift:"transfer_id,3" frugal:"3,default,string" json:"transfer_id"`
}

func NewReleaseOrderReq() *ReleaseOrderReq {
	return &ReleaseOrderReq{}
}

func (p *ReleaseOrderReq) InitDefault() {
}

func (p *ReleaseOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *ReleaseOrderReq) GetBuyerAgentId() (v int64) {
	return p.BuyerAgentId
}

func (p *ReleaseOrderReq) GetTransferId() (v string) {
	return p.TransferId
}
func (p *ReleaseOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *ReleaseOrderReq) SetBuyerAgentId(val int64) {
	p.BuyerAgentId = val
}
func (p *ReleaseOrderReq) SetTransferId(val string) {
	p.TransferId = val
}

func (p *ReleaseOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseOrderReq(%+v)", *p)
}

var fieldIDToName_ReleaseOrderReq = map[int16]string{
	1: "order_id",
	2: "buyer_agent_id",
	3: "transfer_id",
}

type ReleaseOrderResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewReleaseOrderResp() *ReleaseOrderResp {
	return &ReleaseOrderResp{}
}

func (p *ReleaseOrderResp) InitDefault() {
}

var ReleaseOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *ReleaseOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ReleaseOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ReleaseOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ReleaseOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ReleaseOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseOrderResp(%+v)", *p)
}

var fieldIDToName_ReleaseOrderResp = map[int16]string{
	255: "base_resp",
}

type GetOrderReq struct {
	OrderId int64 `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	AgentId int64 `thrift:"agent_id,2" frugal:"2,default,i64" json:"agent_id"`
}

func NewGetOrderReq() *GetOrderReq {
	return &GetOrderReq{}
}

func (p *GetOrderReq) InitDefault() {
}

func (p *GetOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *GetOrderReq) GetAgentId() (v int64) {
	return p.AgentId
}
func (p *GetOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *GetOrderReq) SetAgentId(val int64) {
	p.AgentId = val
}

func (p *GetOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderReq(%+v)", *p)
}

var fieldIDToName_GetOrderReq = map[int16]string{
	1: "order_id",
	2: "agent_id",
}

type GetOrderResp struct {
	Order    *TradeOrder        `thrift:"order,1" frugal:"1,default,TradeOrder" json:"order"`
	Events   []*TradeOrderEvent `thrift:"events,2" frugal:"2,default,list<TradeOrderEvent>" json:"events"`
	BaseResp *base.BaseResp     `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetOrderResp() *GetOrderResp {
	return &GetOrderResp{}
}

func (p *GetOrderResp) InitDefault() {
}

var GetOrderResp_Order_DEFAULT *TradeOrder

func (p *GetOrderResp) GetOrder() (v *TradeOrder) {
	if !p.IsSetOrder() {
		return GetOrderResp_Order_DEFAULT
	}
	return p.Order
}

func (p *GetOrderResp) GetEvents() (v []*TradeOrderEvent) {
	return p.Events
}

var GetOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetOrderResp) SetOrder(val *TradeOrder) {
	p.Order = val
}
func (p *GetOrderResp) SetEvents(val []*TradeOrderEvent) {
	p.Events = val
}
func (p *GetOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetOrderResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResp(%+v)", *p)
}

var fieldIDToName_GetOrderResp = map[int16]string{
	1:   "order",
	2:   "events",
	255: "base_resp",
}

type ListOrdersReq struct {
	AgentId      int64  `thrift:"agent_id,1" frugal:"1,default,i64" json:"agent_id"`
	Role         string `thrift:"role,2" frugal:"2,default,string" json:"role"`
	StatusFilter int16  `thrift:"status_filter,3" frugal:"3,default,i16" json:"status_filter"`
	Limit        int32  `thrift:"limit,4" frugal:"4,default,i32" json:"limit"`
	Cursor       string `thrift:"cursor,5" frugal:"5,default,string" json:"cursor"`
}

func NewListOrdersReq() *ListOrdersReq {
	return &ListOrdersReq{}
}

func (p *ListOrdersReq) InitDefault() {
}

func (p *ListOrdersReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *ListOrdersReq) GetRole() (v string) {
	return p.Role
}

func (p *ListOrdersReq) GetStatusFilter() (v int16) {
	return p.StatusFilter
}

func (p *ListOrdersReq) GetLimit() (v int32) {
	return p.Limit
}

func (p *ListOrdersReq) GetCursor() (v string) {
	return p.Cursor
}
func (p *ListOrdersReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListOrdersReq) SetRole(val string) {
	p.Role = val
}
func (p *ListOrdersReq) SetStatusFilter(val int16) {
	p.StatusFilter = val
}
func (p *ListOrdersReq) SetLimit(val int32) {
	p.Limit = val
}
func (p *ListOrdersReq) SetCursor(val string) {
	p.Cursor = val
}

func (p *ListOrdersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersReq(%+v)", *p)
}

var fieldIDToName_ListOrdersReq = map[int16]string{
	1: "agent_id",
	2: "role",
	3: "status_filter",
	4: "limit",
	5: "cursor",
}

type ListOrdersResp struct {
	Orders     []*TradeOrder  `thrift:"orders,1" frugal:"1,default,list<TradeOrder>" json:"orders"`
	NextCursor string         `thrift:"next_cursor,2" frugal:"2,default,string" json:"next_cursor"`
	BaseResp   *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewListOrdersResp() *ListOrdersResp {
	return &ListOrdersResp{}
}

func (p *ListOrdersResp) InitDefault() {
}

func (p *ListOrdersResp) GetOrders() (v []*TradeOrder) {
	return p.Orders
}

func (p *ListOrdersResp) GetNextCursor() (v string) {
	return p.NextCursor
}

var ListOrdersResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListOrdersResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListOrdersResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListOrdersResp) SetOrders(val []*TradeOrder) {
	p.Orders = val
}
func (p *ListOrdersResp) SetNextCursor(val string) {
	p.NextCursor = val
}
func (p *ListOrdersResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListOrdersResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListOrdersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResp(%+v)", *p)
}

var fieldIDToName_ListOrdersResp = map[int16]string{
	1:   "orders",
	2:   "next_cursor",
	255: "base_resp",
}

type GetGateStatusReq struct {
	BuyerAgentId int64 `thrift:"buyer_agent_id,1" frugal:"1,default,i64" json:"buyer_agent_id"`
}

func NewGetGateStatusReq() *GetGateStatusReq {
	return &GetGateStatusReq{}
}

func (p *GetGateStatusReq) InitDefault() {
}

func (p *GetGateStatusReq) GetBuyerAgentId() (v int64) {
	return p.BuyerAgentId
}
func (p *GetGateStatusReq) SetBuyerAgentId(val int64) {
	p.BuyerAgentId = val
}

func (p *GetGateStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGateStatusReq(%+v)", *p)
}

var fieldIDToName_GetGateStatusReq = map[int16]string{
	1: "buyer_agent_id",
}

type GetGateStatusResp struct {
	CanCreateOrder    bool           `thrift:"can_create_order,1" frugal:"1,default,bool" json:"can_create_order"`
	ActiveOrderCount  int32          `thrift:"active_order_count,2" frugal:"2,default,i32" json:"active_order_count"`
	MaxActiveOrders   int32          `thrift:"max_active_orders,3" frugal:"3,default,i32" json:"max_active_orders"`
	HasPendingRelease bool           `thrift:"has_pending_release,4" frugal:"4,default,bool" json:"has_pending_release"`
	UnpaidOrderCount  int32          `thrift:"unpaid_order_count,5" frugal:"5,default,i32" json:"unpaid_order_count"`
	BaseResp          *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetGateStatusResp() *GetGateStatusResp {
	return &GetGateStatusResp{}
}

func (p *GetGateStatusResp) InitDefault() {
}

func (p *GetGateStatusResp) GetCanCreateOrder() (v bool) {
	return p.CanCreateOrder
}

func (p *GetGateStatusResp) GetActiveOrderCount() (v int32) {
	return p.ActiveOrderCount
}

func (p *GetGateStatusResp) GetMaxActiveOrders() (v int32) {
	return p.MaxActiveOrders
}

func (p *GetGateStatusResp) GetHasPendingRelease() (v bool) {
	return p.HasPendingRelease
}

func (p *GetGateStatusResp) GetUnpaidOrderCount() (v int32) {
	return p.UnpaidOrderCount
}

var GetGateStatusResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetGateStatusResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetGateStatusResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetGateStatusResp) SetCanCreateOrder(val bool) {
	p.CanCreateOrder = val
}
func (p *GetGateStatusResp) SetActiveOrderCount(val int32) {
	p.ActiveOrderCount = val
}
func (p *GetGateStatusResp) SetMaxActiveOrders(val int32) {
	p.MaxActiveOrders = val
}
func (p *GetGateStatusResp) SetHasPendingRelease(val bool) {
	p.HasPendingRelease = val
}
func (p *GetGateStatusResp) SetUnpaidOrderCount(val int32) {
	p.UnpaidOrderCount = val
}
func (p *GetGateStatusResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetGateStatusResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetGateStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGateStatusResp(%+v)", *p)
}

var fieldIDToName_GetGateStatusResp = map[int16]string{
	1:   "can_create_order",
	2:   "active_order_count",
	3:   "max_active_orders",
	4:   "has_pending_release",
	5:   "unpaid_order_count",
	255: "base_resp",
}

type TradeService interface {
	PublishService(ctx context.Context, req *PublishServiceReq) (r *PublishServiceResp, err error)

	UpdateService(ctx context.Context, req *UpdateServiceReq) (r *UpdateServiceResp, err error)

	OfflineService(ctx context.Context, req *OfflineServiceReq) (r *OfflineServiceResp, err error)

	GetMyServices(ctx context.Context, req *GetMyServicesReq) (r *GetMyServicesResp, err error)

	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	DeliverOrder(ctx context.Context, req *DeliverOrderReq) (r *DeliverOrderResp, err error)

	ReleaseOrder(ctx context.Context, req *ReleaseOrderReq) (r *ReleaseOrderResp, err error)

	GetOrder(ctx context.Context, req *GetOrderReq) (r *GetOrderResp, err error)

	ListOrders(ctx context.Context, req *ListOrdersReq) (r *ListOrdersResp, err error)

	GetGateStatus(ctx context.Context, req *GetGateStatusReq) (r *GetGateStatusResp, err error)
}

type TradeServicePublishServiceArgs struct {
	Req *PublishServiceReq `thrift:"req,1" frugal:"1,default,PublishServiceReq" json:"req"`
}

func NewTradeServicePublishServiceArgs() *TradeServicePublishServiceArgs {
	return &TradeServicePublishServiceArgs{}
}

func (p *TradeServicePublishServiceArgs) InitDefault() {
}

var TradeServicePublishServiceArgs_Req_DEFAULT *PublishServiceReq

func (p *TradeServicePublishServiceArgs) GetReq() (v *PublishServiceReq) {
	if !p.IsSetReq() {
		return TradeServicePublishServiceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServicePublishServiceArgs) SetReq(val *PublishServiceReq) {
	p.Req = val
}

func (p *TradeServicePublishServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServicePublishServiceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServicePublishServiceArgs(%+v)", *p)
}

var fieldIDToName_TradeServicePublishServiceArgs = map[int16]string{
	1: "req",
}

type TradeServicePublishServiceResult struct {
	Success *PublishServiceResp `thrift:"success,0,optional" frugal:"0,optional,PublishServiceResp" json:"success,omitempty"`
}

func NewTradeServicePublishServiceResult() *TradeServicePublishServiceResult {
	return &TradeServicePublishServiceResult{}
}

func (p *TradeServicePublishServiceResult) InitDefault() {
}

var TradeServicePublishServiceResult_Success_DEFAULT *PublishServiceResp

func (p *TradeServicePublishServiceResult) GetSuccess() (v *PublishServiceResp) {
	if !p.IsSetSuccess() {
		return TradeServicePublishServiceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServicePublishServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublishServiceResp)
}

func (p *TradeServicePublishServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServicePublishServiceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServicePublishServiceResult(%+v)", *p)
}

var fieldIDToName_TradeServicePublishServiceResult = map[int16]string{
	0: "success",
}

type TradeServiceUpdateServiceArgs struct {
	Req *UpdateServiceReq `thrift:"req,1" frugal:"1,default,UpdateServiceReq" json:"req"`
}

func NewTradeServiceUpdateServiceArgs() *TradeServiceUpdateServiceArgs {
	return &TradeServiceUpdateServiceArgs{}
}

func (p *TradeServiceUpdateServiceArgs) InitDefault() {
}

var TradeServiceUpdateServiceArgs_Req_DEFAULT *UpdateServiceReq

func (p *TradeServiceUpdateServiceArgs) GetReq() (v *UpdateServiceReq) {
	if !p.IsSetReq() {
		return TradeServiceUpdateServiceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceUpdateServiceArgs) SetReq(val *UpdateServiceReq) {
	p.Req = val
}

func (p *TradeServiceUpdateServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceUpdateServiceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceUpdateServiceArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceUpdateServiceArgs = map[int16]string{
	1: "req",
}

type TradeServiceUpdateServiceResult struct {
	Success *UpdateServiceResp `thrift:"success,0,optional" frugal:"0,optional,UpdateServiceResp" json:"success,omitempty"`
}

func NewTradeServiceUpdateServiceResult() *TradeServiceUpdateServiceResult {
	return &TradeServiceUpdateServiceResult{}
}

func (p *TradeServiceUpdateServiceResult) InitDefault() {
}

var TradeServiceUpdateServiceResult_Success_DEFAULT *UpdateServiceResp

func (p *TradeServiceUpdateServiceResult) GetSuccess() (v *UpdateServiceResp) {
	if !p.IsSetSuccess() {
		return TradeServiceUpdateServiceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceUpdateServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateServiceResp)
}

func (p *TradeServiceUpdateServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceUpdateServiceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceUpdateServiceResult(%+v)", *p)
}

var fieldIDToName_TradeServiceUpdateServiceResult = map[int16]string{
	0: "success",
}

type TradeServiceOfflineServiceArgs struct {
	Req *OfflineServiceReq `thrift:"req,1" frugal:"1,default,OfflineServiceReq" json:"req"`
}

func NewTradeServiceOfflineServiceArgs() *TradeServiceOfflineServiceArgs {
	return &TradeServiceOfflineServiceArgs{}
}

func (p *TradeServiceOfflineServiceArgs) InitDefault() {
}

var TradeServiceOfflineServiceArgs_Req_DEFAULT *OfflineServiceReq

func (p *TradeServiceOfflineServiceArgs) GetReq() (v *OfflineServiceReq) {
	if !p.IsSetReq() {
		return TradeServiceOfflineServiceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceOfflineServiceArgs) SetReq(val *OfflineServiceReq) {
	p.Req = val
}

func (p *TradeServiceOfflineServiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceOfflineServiceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceOfflineServiceArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceOfflineServiceArgs = map[int16]string{
	1: "req",
}

type TradeServiceOfflineServiceResult struct {
	Success *OfflineServiceResp `thrift:"success,0,optional" frugal:"0,optional,OfflineServiceResp" json:"success,omitempty"`
}

func NewTradeServiceOfflineServiceResult() *TradeServiceOfflineServiceResult {
	return &TradeServiceOfflineServiceResult{}
}

func (p *TradeServiceOfflineServiceResult) InitDefault() {
}

var TradeServiceOfflineServiceResult_Success_DEFAULT *OfflineServiceResp

func (p *TradeServiceOfflineServiceResult) GetSuccess() (v *OfflineServiceResp) {
	if !p.IsSetSuccess() {
		return TradeServiceOfflineServiceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceOfflineServiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*OfflineServiceResp)
}

func (p *TradeServiceOfflineServiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceOfflineServiceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceOfflineServiceResult(%+v)", *p)
}

var fieldIDToName_TradeServiceOfflineServiceResult = map[int16]string{
	0: "success",
}

type TradeServiceGetMyServicesArgs struct {
	Req *GetMyServicesReq `thrift:"req,1" frugal:"1,default,GetMyServicesReq" json:"req"`
}

func NewTradeServiceGetMyServicesArgs() *TradeServiceGetMyServicesArgs {
	return &TradeServiceGetMyServicesArgs{}
}

func (p *TradeServiceGetMyServicesArgs) InitDefault() {
}

var TradeServiceGetMyServicesArgs_Req_DEFAULT *GetMyServicesReq

func (p *TradeServiceGetMyServicesArgs) GetReq() (v *GetMyServicesReq) {
	if !p.IsSetReq() {
		return TradeServiceGetMyServicesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceGetMyServicesArgs) SetReq(val *GetMyServicesReq) {
	p.Req = val
}

func (p *TradeServiceGetMyServicesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceGetMyServicesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetMyServicesArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceGetMyServicesArgs = map[int16]string{
	1: "req",
}

type TradeServiceGetMyServicesResult struct {
	Success *GetMyServicesResp `thrift:"success,0,optional" frugal:"0,optional,GetMyServicesResp" json:"success,omitempty"`
}

func NewTradeServiceGetMyServicesResult() *TradeServiceGetMyServicesResult {
	return &TradeServiceGetMyServicesResult{}
}

func (p *TradeServiceGetMyServicesResult) InitDefault() {
}

var TradeServiceGetMyServicesResult_Success_DEFAULT *GetMyServicesResp

func (p *TradeServiceGetMyServicesResult) GetSuccess() (v *GetMyServicesResp) {
	if !p.IsSetSuccess() {
		return TradeServiceGetMyServicesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceGetMyServicesResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMyServicesResp)
}

func (p *TradeServiceGetMyServicesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceGetMyServicesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetMyServicesResult(%+v)", *p)
}

var fieldIDToName_TradeServiceGetMyServicesResult = map[int16]string{
	0: "success",
}

type TradeServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewTradeServiceCreateOrderArgs() *TradeServiceCreateOrderArgs {
	return &TradeServiceCreateOrderArgs{}
}

func (p *TradeServiceCreateOrderArgs) InitDefault() {
}

var TradeServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *TradeServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return TradeServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *TradeServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type TradeServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewTradeServiceCreateOrderResult() *TradeServiceCreateOrderResult {
	return &TradeServiceCreateOrderResult{}
}

func (p *TradeServiceCreateOrderResult) InitDefault() {
}

var TradeServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *TradeServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return TradeServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *TradeServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_TradeServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type TradeServiceDeliverOrderArgs struct {
	Req *DeliverOrderReq `thrift:"req,1" frugal:"1,default,DeliverOrderReq" json:"req"`
}

func NewTradeServiceDeliverOrderArgs() *TradeServiceDeliverOrderArgs {
	return &TradeServiceDeliverOrderArgs{}
}

func (p *TradeServiceDeliverOrderArgs) InitDefault() {
}

var TradeServiceDeliverOrderArgs_Req_DEFAULT *DeliverOrderReq

func (p *TradeServiceDeliverOrderArgs) GetReq() (v *DeliverOrderReq) {
	if !p.IsSetReq() {
		return TradeServiceDeliverOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceDeliverOrderArgs) SetReq(val *DeliverOrderReq) {
	p.Req = val
}

func (p *TradeServiceDeliverOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceDeliverOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceDeliverOrderArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceDeliverOrderArgs = map[int16]string{
	1: "req",
}

type TradeServiceDeliverOrderResult struct {
	Success *DeliverOrderResp `thrift:"success,0,optional" frugal:"0,optional,DeliverOrderResp" json:"success,omitempty"`
}

func NewTradeServiceDeliverOrderResult() *TradeServiceDeliverOrderResult {
	return &TradeServiceDeliverOrderResult{}
}

func (p *TradeServiceDeliverOrderResult) InitDefault() {
}

var TradeServiceDeliverOrderResult_Success_DEFAULT *DeliverOrderResp

func (p *TradeServiceDeliverOrderResult) GetSuccess() (v *DeliverOrderResp) {
	if !p.IsSetSuccess() {
		return TradeServiceDeliverOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceDeliverOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeliverOrderResp)
}

func (p *TradeServiceDeliverOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceDeliverOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceDeliverOrderResult(%+v)", *p)
}

var fieldIDToName_TradeServiceDeliverOrderResult = map[int16]string{
	0: "success",
}

type TradeServiceReleaseOrderArgs struct {
	Req *ReleaseOrderReq `thrift:"req,1" frugal:"1,default,ReleaseOrderReq" json:"req"`
}

func NewTradeServiceReleaseOrderArgs() *TradeServiceReleaseOrderArgs {
	return &TradeServiceReleaseOrderArgs{}
}

func (p *TradeServiceReleaseOrderArgs) InitDefault() {
}

var TradeServiceReleaseOrderArgs_Req_DEFAULT *ReleaseOrderReq

func (p *TradeServiceReleaseOrderArgs) GetReq() (v *ReleaseOrderReq) {
	if !p.IsSetReq() {
		return TradeServiceReleaseOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceReleaseOrderArgs) SetReq(val *ReleaseOrderReq) {
	p.Req = val
}

func (p *TradeServiceReleaseOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceReleaseOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceReleaseOrderArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceReleaseOrderArgs = map[int16]string{
	1: "req",
}

type TradeServiceReleaseOrderResult struct {
	Success *ReleaseOrderResp `thrift:"success,0,optional" frugal:"0,optional,ReleaseOrderResp" json:"success,omitempty"`
}

func NewTradeServiceReleaseOrderResult() *TradeServiceReleaseOrderResult {
	return &TradeServiceReleaseOrderResult{}
}

func (p *TradeServiceReleaseOrderResult) InitDefault() {
}

var TradeServiceReleaseOrderResult_Success_DEFAULT *ReleaseOrderResp

func (p *TradeServiceReleaseOrderResult) GetSuccess() (v *ReleaseOrderResp) {
	if !p.IsSetSuccess() {
		return TradeServiceReleaseOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceReleaseOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReleaseOrderResp)
}

func (p *TradeServiceReleaseOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceReleaseOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceReleaseOrderResult(%+v)", *p)
}

var fieldIDToName_TradeServiceReleaseOrderResult = map[int16]string{
	0: "success",
}

type TradeServiceGetOrderArgs struct {
	Req *GetOrderReq `thrift:"req,1" frugal:"1,default,GetOrderReq" json:"req"`
}

func NewTradeServiceGetOrderArgs() *TradeServiceGetOrderArgs {
	return &TradeServiceGetOrderArgs{}
}

func (p *TradeServiceGetOrderArgs) InitDefault() {
}

var TradeServiceGetOrderArgs_Req_DEFAULT *GetOrderReq

func (p *TradeServiceGetOrderArgs) GetReq() (v *GetOrderReq) {
	if !p.IsSetReq() {
		return TradeServiceGetOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceGetOrderArgs) SetReq(val *GetOrderReq) {
	p.Req = val
}

func (p *TradeServiceGetOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceGetOrderArgs = map[int16]string{
	1: "req",
}

type TradeServiceGetOrderResult struct {
	Success *GetOrderResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderResp" json:"success,omitempty"`
}

func NewTradeServiceGetOrderResult() *TradeServiceGetOrderResult {
	return &TradeServiceGetOrderResult{}
}

func (p *TradeServiceGetOrderResult) InitDefault() {
}

var TradeServiceGetOrderResult_Success_DEFAULT *GetOrderResp

func (p *TradeServiceGetOrderResult) GetSuccess() (v *GetOrderResp) {
	if !p.IsSetSuccess() {
		return TradeServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResp)
}

func (p *TradeServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_TradeServiceGetOrderResult = map[int16]string{
	0: "success",
}

type TradeServiceListOrdersArgs struct {
	Req *ListOrdersReq `thrift:"req,1" frugal:"1,default,ListOrdersReq" json:"req"`
}

func NewTradeServiceListOrdersArgs() *TradeServiceListOrdersArgs {
	return &TradeServiceListOrdersArgs{}
}

func (p *TradeServiceListOrdersArgs) InitDefault() {
}

var TradeServiceListOrdersArgs_Req_DEFAULT *ListOrdersReq

func (p *TradeServiceListOrdersArgs) GetReq() (v *ListOrdersReq) {
	if !p.IsSetReq() {
		return TradeServiceListOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceListOrdersArgs) SetReq(val *ListOrdersReq) {
	p.Req = val
}

func (p *TradeServiceListOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceListOrdersArgs = map[int16]string{
	1: "req",
}

type TradeServiceListOrdersResult struct {
	Success *ListOrdersResp `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResp" json:"success,omitempty"`
}

func NewTradeServiceListOrdersResult() *TradeServiceListOrdersResult {
	return &TradeServiceListOrdersResult{}
}

func (p *TradeServiceListOrdersResult) InitDefault() {
}

var TradeServiceListOrdersResult_Success_DEFAULT *ListOrdersResp

func (p *TradeServiceListOrdersResult) GetSuccess() (v *ListOrdersResp) {
	if !p.IsSetSuccess() {
		return TradeServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResp)
}

func (p *TradeServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_TradeServiceListOrdersResult = map[int16]string{
	0: "success",
}

type TradeServiceGetGateStatusArgs struct {
	Req *GetGateStatusReq `thrift:"req,1" frugal:"1,default,GetGateStatusReq" json:"req"`
}

func NewTradeServiceGetGateStatusArgs() *TradeServiceGetGateStatusArgs {
	return &TradeServiceGetGateStatusArgs{}
}

func (p *TradeServiceGetGateStatusArgs) InitDefault() {
}

var TradeServiceGetGateStatusArgs_Req_DEFAULT *GetGateStatusReq

func (p *TradeServiceGetGateStatusArgs) GetReq() (v *GetGateStatusReq) {
	if !p.IsSetReq() {
		return TradeServiceGetGateStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TradeServiceGetGateStatusArgs) SetReq(val *GetGateStatusReq) {
	p.Req = val
}

func (p *TradeServiceGetGateStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TradeServiceGetGateStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetGateStatusArgs(%+v)", *p)
}

var fieldIDToName_TradeServiceGetGateStatusArgs = map[int16]string{
	1: "req",
}

type TradeServiceGetGateStatusResult struct {
	Success *GetGateStatusResp `thrift:"success,0,optional" frugal:"0,optional,GetGateStatusResp" json:"success,omitempty"`
}

func NewTradeServiceGetGateStatusResult() *TradeServiceGetGateStatusResult {
	return &TradeServiceGetGateStatusResult{}
}

func (p *TradeServiceGetGateStatusResult) InitDefault() {
}

var TradeServiceGetGateStatusResult_Success_DEFAULT *GetGateStatusResp

func (p *TradeServiceGetGateStatusResult) GetSuccess() (v *GetGateStatusResp) {
	if !p.IsSetSuccess() {
		return TradeServiceGetGateStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TradeServiceGetGateStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetGateStatusResp)
}

func (p *TradeServiceGetGateStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TradeServiceGetGateStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TradeServiceGetGateStatusResult(%+v)", *p)
}

var fieldIDToName_TradeServiceGetGateStatusResult = map[int16]string{
	0: "success",
}
