// Code generated by hertz generator.

package console

import (
	"context"

	console "eigenflux_server/api/model/eigenflux/console"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ListAgents .
// @router /console/api/v1/agents [GET]
func ListAgents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ListAgentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ListAgentsResp)

	c.JSON(consts.StatusOK, resp)
}

// ListItems .
// @router /console/api/v1/items [GET]
func ListItems(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ListItemsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ListItemsResp)

	c.JSON(consts.StatusOK, resp)
}

// ListAgentImprItems .
// @router /console/api/v1/impr/items [GET]
func ListAgentImprItems(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ListAgentImprItemsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ListAgentImprItemsResp)

	c.JSON(consts.StatusOK, resp)
}

// ListMilestoneRules .
// @router /console/api/v1/milestone-rules [GET]
func ListMilestoneRules(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ListMilestoneRulesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ListMilestoneRulesResp)

	c.JSON(consts.StatusOK, resp)
}

// CreateMilestoneRule .
// @router /console/api/v1/milestone-rules [POST]
func CreateMilestoneRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.CreateMilestoneRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.MilestoneRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateMilestoneRule .
// @router /console/api/v1/milestone-rules/:rule_id [PUT]
func UpdateMilestoneRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.UpdateMilestoneRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.MilestoneRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// ReplaceMilestoneRule .
// @router /console/api/v1/milestone-rules/:rule_id/replace [POST]
func ReplaceMilestoneRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ReplaceMilestoneRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ReplaceMilestoneRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// ListSystemNotifications .
// @router /console/api/v1/system-notifications [GET]
func ListSystemNotifications(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.ListSystemNotificationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.ListSystemNotificationsResp)

	c.JSON(consts.StatusOK, resp)
}

// CreateSystemNotification .
// @router /console/api/v1/system-notifications [POST]
func CreateSystemNotification(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.CreateSystemNotificationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.SystemNotificationResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateSystemNotification .
// @router /console/api/v1/system-notifications/:notification_id [PUT]
func UpdateSystemNotification(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.UpdateSystemNotificationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.SystemNotificationResp)

	c.JSON(consts.StatusOK, resp)
}

// OfflineSystemNotification .
// @router /console/api/v1/system-notifications/:notification_id/offline [POST]
func OfflineSystemNotification(ctx context.Context, c *app.RequestContext) {
	var err error
	var req console.OfflineSystemNotificationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(console.SystemNotificationResp)

	c.JSON(consts.StatusOK, resp)
}
