package cmd

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"strconv"
	"time"

	"cli.eigenflux.ai/internal/auth"
	"cli.eigenflux.ai/internal/dispatch"
)

// The subscribed seller has authorized contractual fulfillment. Persist before
// the first remote mutation and never automatically replay uncertain delivery.
func (w *accountWatch) deliverCommissionArtifacts(ctx context.Context, job dispatch.Job, order commissionIntakeOrder, result dispatch.CommissionFulfillmentResult, session string) error {
	files, cleanup, err := freezeCommissionArtifacts(result)
	if err != nil {
		return w.finishDispatch(job, "failed", "commission_fulfillment_artifacts_invalid", session, "")
	}
	defer cleanup()
	api, err := w.commissionAPI(ctx)
	if err != nil {
		return w.finishDispatch(job, "failed", "identity_changed", session, "")
	}
	id := strconv.FormatInt(int64(order.OrderID), 10)
	return auth.WithV2CredentialsLockContext(ctx, w.server.Name, 35*time.Second, func() error {
		if err := w.commissionIdentityOK(); err != nil {
			return err
		}
		credentials, err := auth.LoadV2Credentials(w.server.Name)
		if err != nil {
			return err
		}
		api.Token, api.OnUnauthorized = credentials.AccessToken, nil
		readOrder := func() (commissionIntakeOrder, error) {
			response, err := api.Get("/orders/"+id, nil)
			var data struct {
				Order commissionIntakeOrder `json:"order"`
			}
			if err != nil {
				return data.Order, err
			}
			if response.Code != 0 || json.Unmarshal(response.Data, &data) != nil {
				return data.Order, errors.New("commission_delivery_order_unavailable")
			}
			return data.Order, nil
		}
		before, err := readOrder()
		if err != nil || !sameCommissionIntakeOrder(order, before) || ctx.Err() != nil || w.commissionIdentityOK() != nil {
			return w.finishDispatch(job, "failed", "commission_fulfillment_order_changed", session, "")
		}
		if err := w.journal.BeginCommissionDelivery(job.ID, result, session); err != nil {
			return err
		}
		uncertain := func() error { return w.finishDispatch(job, "unknown", "commission_delivery_unconfirmed", session, "") }
		base := "/orders/" + id
		// Operator-approved retries create a new persisted output directory. Keep
		// each attempt stable without binding regenerated bytes to an old grant.
		key := childMutationKey("watch-delivery-"+job.ID, result.OutputDirectory)
		for _, file := range files {
			if ctx.Err() != nil || w.commissionIdentityOK() != nil {
				return uncertain()
			}
			if err := uploadMaterial(ctx, api, base, key, file); err != nil {
				return uncertain()
			}
		}
		before, err = readOrder()
		if err != nil || !sameCommissionIntakeOrder(order, before) || ctx.Err() != nil || w.commissionIdentityOK() != nil {
			return uncertain()
		}
		response, err := api.PostWithHeaders(base+"/deliver", map[string]any{"expected_version": order.Version, "output_files": files}, map[string]string{idempotencyHeader: childMutationKey(key, "deliver")})
		if err != nil || response.Code != 0 {
			return uncertain()
		}
		confirmed, err := readOrder()
		if err != nil || confirmed.OrderID != order.OrderID || confirmed.SellerID != order.SellerID || confirmed.BuyerID != order.BuyerID || confirmed.Version <= order.Version {
			return uncertain()
		}
		switch confirmed.State {
		case "validating", "awaiting_buyer_confirmation", "completed":
			return w.finishDispatch(job, "completed", "commission_delivery_confirmed", session, "")
		default:
			return uncertain()
		}
	})
}

// Copy only the verified bounded bytes through a confined root. Uploads never
// reopen an Agent-controlled path after the digest check.
func freezeCommissionArtifacts(result dispatch.CommissionFulfillmentResult) ([]materialFile, func(), error) {
	noop := func() {}
	root, err := os.OpenRoot(result.OutputDirectory)
	if err != nil {
		return nil, noop, err
	}
	defer root.Close()
	dir, err := os.MkdirTemp("", "eigenflux-delivery-")
	if err != nil {
		return nil, noop, err
	}
	cleanup := func() { _ = os.RemoveAll(dir) }
	files := make([]materialFile, 0, len(result.Artifacts))
	for index, artifact := range result.Artifacts {
		if _, err := commissionArtifactPathInfo(root, artifact.RelativePath); err != nil {
			cleanup()
			return nil, noop, err
		}
		file, err := root.Open(artifact.RelativePath)
		if err != nil {
			cleanup()
			return nil, noop, err
		}
		data, readErr := io.ReadAll(io.LimitReader(file, artifact.ByteSize+1))
		_ = file.Close()
		digest := sha256.Sum256(data)
		if readErr != nil || int64(len(data)) != artifact.ByteSize || hex.EncodeToString(digest[:]) != artifact.SHA256 {
			cleanup()
			return nil, noop, errors.New("commission_artifact_changed")
		}
		local := dir + "/" + strconv.Itoa(index)
		if err := os.WriteFile(local, data, 0600); err != nil {
			cleanup()
			return nil, noop, err
		}
		files = append(files, materialFile{LogicalPath: artifact.LogicalPath, SHA256: artifact.SHA256, ByteSize: artifact.ByteSize, LocalPath: local})
	}
	return files, cleanup, nil
}
