// Code generated by hertz generator.

package console

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentimpritemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmilestonerulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmilestoneruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemilestoneruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _replacemilestoneruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsystemnotificationsMw() []app.HandlerFunc {
	return nil
}

func _createsystemnotificationMw() []app.HandlerFunc {
	return nil
}

func _updatesystemnotificationMw() []app.HandlerFunc {
	return nil
}

func _offlinesystemnotificationMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _milestone_rulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rule_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _system_notificationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notification_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imprMw() []app.HandlerFunc {
	// your code...
	return nil
}
