package consolev2

import (
	"context"
	"net"
	"net/http"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	redis "github.com/redis/go-redis/v9"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var otpRetryV2ReleaseRedis = redis.NewScript(`
if redis.call('GET', KEYS[1]) ~= ARGV[1] then return 0 end
return redis.call('DEL', KEYS[1])
`)

// DB14 was empty before the lease was acquired, and each subtest creates only
// bounded fixture keys. Check ownership and delete atomically so a stale owner
// cannot clear a successor's keys after its lease expires.
var otpRetryV2ClearRedis = redis.NewScript(`
if redis.call('GET', KEYS[1]) ~= ARGV[1] then return 0 end
local keys = redis.call('KEYS', '*')
if #keys > 256 then return -1 end
for _, key in ipairs(keys) do redis.call('DEL', key) end
return 1
`)

type otpRetryV2Fixture struct {
	db    *gorm.DB
	svc   *Service
	http  *server.Hertz
	email string
}

func newOTPRetryV2Fixture(t *testing.T) *otpRetryV2Fixture {
	t.Helper()
	dsn, addr := os.Getenv("AUTH_RETRY_PG_DSN"), os.Getenv("AUTH_RETRY_REDIS_ADDR")
	if dsn == "" || addr == "" {
		t.Skip("AUTH_RETRY_PG_DSN and AUTH_RETRY_REDIS_ADDR are required for native OTP boundaries")
	}
	cfg, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatal("invalid OTP fixture PostgreSQL configuration")
	}
	host, _, err := net.SplitHostPort(addr)
	if err != nil || (host != "127.0.0.1" && host != "localhost" && host != "::1") ||
		(cfg.Host != "127.0.0.1" && cfg.Host != "localhost" && cfg.Host != "::1") {
		t.Fatal("OTP fixtures require explicit loopback PostgreSQL and Redis endpoints")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	rdb := redis.NewClient(&redis.Options{Addr: addr, DB: 14})
	owner := uuid.NewString()
	const lease = "arena:otp-retry:test-owner"
	for {
		locked, lockErr := rdb.SetNX(ctx, lease, owner, 2*time.Minute).Result()
		if lockErr != nil {
			rdb.Close()
			t.Fatalf("OTP fixture Redis unavailable: %v", lockErr)
		}
		if locked {
			break
		}
		select {
		case <-ctx.Done():
			rdb.Close()
			t.Fatal("OTP Redis DB14 is owned by another running test")
		case <-time.After(20 * time.Millisecond):
		}
	}
	if count, sizeErr := rdb.DBSize(ctx).Result(); sizeErr != nil || count != 1 {
		otpRetryV2ReleaseRedis.Run(ctx, rdb, []string{lease}, owner)
		rdb.Close()
		t.Fatal("OTP Redis DB14 must be empty before its fixture lease is acquired")
	}
	t.Cleanup(func() {
		cleanup, stop := context.WithTimeout(context.Background(), 5*time.Second)
		defer stop()
		if cleared, err := otpRetryV2ClearRedis.Run(cleanup, rdb, []string{lease}, owner).Int(); err != nil {
			t.Errorf("OTP DB14 cleanup failed: %v", err)
		} else if cleared != 1 {
			t.Error("lost ownership or unexpected key count in OTP Redis fixture; refusing to clear DB14")
		}
		rdb.Close()
	})
	admin, err := gorm.Open(postgres.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		t.Fatal(err)
	}
	adminSQL, err := admin.DB()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { adminSQL.Close() })
	schema := "otp_retry_v2_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	quoted := pgx.Identifier{schema}.Sanitize()
	if err := admin.Exec("CREATE SCHEMA " + quoted).Error; err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := admin.Exec("DROP SCHEMA " + quoted + " CASCADE").Error; err != nil {
			t.Errorf("OTP schema cleanup failed: %v", err)
		}
	})
	for _, table := range []string{"agents", "v2_email_challenges", "agent_email_bindings", "agent_principals", "console_v2_sessions", "agent_context_heads", "agent_onboarding_v2", "agent_feed_v2_settings", "agent_onboarding_drafts"} {
		name := pgx.Identifier{schema, table}.Sanitize()
		if err := admin.Exec("CREATE TABLE " + name + " (LIKE public." + pgx.Identifier{table}.Sanitize() + " INCLUDING ALL)").Error; err != nil {
			t.Fatal(err)
		}
		var columns []string
		if err := admin.Raw(`SELECT column_name FROM information_schema.columns
			WHERE table_schema = ? AND table_name = ? AND column_default LIKE 'nextval(%'`, schema, table).Scan(&columns).Error; err != nil {
			t.Fatal(err)
		}
		for _, column := range columns {
			col := pgx.Identifier{column}.Sanitize()
			if err := admin.Exec("ALTER TABLE " + name + " ALTER COLUMN " + col + " DROP DEFAULT, ALTER COLUMN " + col + " ADD GENERATED BY DEFAULT AS IDENTITY").Error; err != nil {
				t.Fatal(err)
			}
		}
	}
	cfg.RuntimeParams["search_path"] = schema
	cfg.RuntimeParams["statement_timeout"] = "5000"
	sqlDB := stdlib.OpenDB(*cfg)
	sqlDB.SetMaxOpenConns(12)
	gdb, err := gorm.Open(postgres.New(postgres.Config{Conn: sqlDB}), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		sqlDB.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() { sqlDB.Close() })
	now := time.Now().UnixMilli()
	emailAddr := "retry-" + uuid.NewString() + "@otp.invalid"
	exec := func(query string, args ...interface{}) {
		t.Helper()
		if err := gdb.Exec(query, args...).Error; err != nil {
			t.Fatal(err)
		}
	}
	exec(`INSERT INTO agents (agent_id,email,email_kind,agent_name,bio,created_at,updated_at) VALUES (101,?,'legacy_real','OTP Fixture','isolated OTP test',?,?)`, emailAddr, now, now)
	exec(`INSERT INTO agent_email_bindings (agent_id,normalized_email,normalization_version,verification_state,status,verified_at,created_at,updated_at) VALUES (101,?,1,'verified','active',?,?,?)`, emailAddr, now, now, now)
	exec(`INSERT INTO agent_principals (agent_id,key_type,key_fingerprint,public_key,status,created_at,last_seen_at) VALUES (101,'ed25519-v1',?,decode(repeat('11',32),'hex'),'active',?,?)`, hashString("otp-fixture-principal"), now, now)
	// Preserve a current owner draft, so email login exercises the lazy state
	// path without pulling profile/Card/RPC concerns into this OTP regression.
	exec(`INSERT INTO agent_onboarding_drafts (agent_id,revision,draft_data,field_provenance,actor_type,request_id,created_at) VALUES (101,1,'{}','{}','system_derived','otp-fixture-draft',?)`, now)
	svc := &Service{db: gdb, otpPepper: "otp-retry-fixture-pepper", testEmailPatterns: []string{"*@otp.invalid"}, testOTP: "123456", publicURL: "https://console.example.test", redisClient: rdb}
	h := server.New(server.WithHostPorts("127.0.0.1:0"))
	svc.Register(h)
	return &otpRetryV2Fixture{db: gdb, svc: svc, http: h, email: emailAddr}
}

func (f *otpRetryV2Fixture) challenge(t *testing.T, emailAddr string) string {
	t.Helper()
	status, payload, _ := performJSON(t, f.http, http.MethodPost, "/api/v2/auth/email/challenges", createEmailChallengeRequest{Email: emailAddr})
	if status != http.StatusAccepted {
		t.Fatalf("email challenge status=%d payload=%#v", status, payload)
	}
	id, ok := responseData(t, payload)["challenge_id"].(string)
	if !ok || id == "" {
		t.Fatal("accepted challenge has no ID")
	}
	return id
}

func (f *otpRetryV2Fixture) verify(t *testing.T, id, emailAddr, code, purpose string) (int, map[string]interface{}, [][]byte) {
	t.Helper()
	return performJSON(t, f.http, http.MethodPost, "/api/v2/auth/email/verify", verifyEmailRequest{ChallengeID: id, Email: emailAddr, OTP: code, Purpose: purpose})
}

func (f *otpRetryV2Fixture) state(t *testing.T, id string) emailChallengeRow {
	t.Helper()
	var row emailChallengeRow
	if err := f.db.Raw(`SELECT challenge_id,purpose,normalized_email_hash,subject_agent_id,console_session_id,otp_hmac,status,attempt_count,max_attempts,expires_at FROM v2_email_challenges WHERE challenge_id=?`, id).Scan(&row).Error; err != nil || row.ChallengeID == "" {
		t.Fatalf("challenge facts unavailable: %v", err)
	}
	return row
}

func (f *otpRetryV2Fixture) sessions(t *testing.T, want int64) {
	t.Helper()
	var count int64
	if err := f.db.Table("console_v2_sessions").Count(&count).Error; err != nil || count != want {
		t.Fatalf("durable Console sessions=%d want=%d err=%v", count, want, err)
	}
	if err := f.db.Table("console_v2_sessions AS cs").Joins("JOIN agent_principals AS p ON p.principal_id = cs.principal_id").
		Where("cs.agent_id = ? AND p.agent_id = ?", 101, 101).Count(&count).Error; err != nil || count != want {
		t.Fatalf("owned Console sessions=%d want=%d err=%v", count, want, err)
	}
}

func assertOTPRetryV2Rejected(t *testing.T, status int, payload map[string]interface{}, cookies [][]byte) {
	t.Helper()
	// Hertz PeekAll(Set-Cookie) returns one empty byte slice when no cookie
	// exists. Count bytes rather than mistaking that container for a session.
	for _, value := range cookies {
		if len(value) != 0 {
			t.Fatal("rejected OTP issued a cookie")
		}
	}
	if status != http.StatusUnauthorized || responseErrorCode(t, payload) != "OTP_INVALID" {
		t.Fatalf("OTP rejection status=%d payload=%#v cookies=%d", status, payload, len(cookies))
	}
}

func hasOTPRetryV2SessionCookie(cookies [][]byte) bool {
	for _, value := range cookies {
		if strings.Contains(string(value), consoleCookieName+"=") {
			return true
		}
	}
	return false
}

func TestAuthRetryV2OTPBoundaries(t *testing.T) {
	for _, name := range []string{"resend_preserves_live_challenges", "expired_old_challenge", "wrong_email", "wrong_purpose", "attempt_limit_then_fresh_challenge", "single_consumption", "concurrent_verify", "concurrent_wrong_codes", "request_limit", "unknown_email_does_not_create_identity", "cleanup_refuses_stale_owner"} {
		t.Run(name, func(t *testing.T) {
			f := newOTPRetryV2Fixture(t)
			id := f.challenge(t, f.email)
			if row := f.state(t, id); row.Status != "pending" || row.AttemptCount != 0 || row.MaxAttempts != 5 || row.ExpiresAt <= time.Now().UnixMilli() {
				t.Fatalf("initial challenge facts=%#v", row)
			}
			switch name {
			case "cleanup_refuses_stale_owner":
				ctx := context.Background()
				rdb := f.svc.redisClient
				const lease = "arena:otp-retry:test-owner"
				owner, err := rdb.Get(ctx, lease).Result()
				if err != nil {
					t.Fatal(err)
				}
				const successorKey = "arena:otp-retry:successor-fixture"
				if err := rdb.Set(ctx, successorKey, "preserve", time.Minute).Err(); err != nil {
					t.Fatal(err)
				}
				for _, script := range []*redis.Script{otpRetryV2ReleaseRedis, otpRetryV2ClearRedis} {
					if cleared, err := script.Run(ctx, rdb, []string{lease}, "expired-owner").Int(); err != nil || cleared != 0 {
						t.Fatalf("stale cleanup=%d err=%v", cleared, err)
					}
					if rdb.Get(ctx, lease).Val() != owner || rdb.Get(ctx, successorKey).Val() != "preserve" {
						t.Fatal("stale owner deleted its successor's lease or fixture key")
					}
				}
			case "resend_preserves_live_challenges":
				// Two fixed fixture codes stand in for successive generated codes.
				// Current V2 creates independent live challenges; this observation
				// does not approve an unresolved latest-code-only product contract.
				f.svc.testOTP = "654321"
				fresh := f.challenge(t, "  "+strings.ToUpper(f.email)+"  ")
				if fresh == id || f.state(t, id).Status != "pending" {
					t.Fatal("resend unexpectedly consumed or replaced the first challenge")
				}
				status, payload, cookies := f.verify(t, fresh, f.email, "123456", "login")
				assertOTPRetryV2Rejected(t, status, payload, cookies)
				f.sessions(t, 0)
				if status, _, _ := f.verify(t, id, f.email, "123456", "login"); status != 200 {
					t.Fatal("still-live first challenge rejected")
				}
				if status, _, _ := f.verify(t, fresh, f.email, "654321", "login"); status != 200 {
					t.Fatal("fresh matching code rejected")
				}
				f.sessions(t, 2)
			case "expired_old_challenge":
				if err := f.db.Exec("UPDATE v2_email_challenges SET expires_at=? WHERE challenge_id=?", time.Now().Add(-time.Minute).UnixMilli(), id).Error; err != nil {
					t.Fatal(err)
				}
				fresh := f.challenge(t, f.email)
				status, payload, cookies := f.verify(t, id, f.email, "123456", "login")
				assertOTPRetryV2Rejected(t, status, payload, cookies)
				f.sessions(t, 0)
				if row := f.state(t, id); row.Status != "pending" || row.AttemptCount != 0 {
					t.Fatal("expired challenge changed without consumption")
				}
				if status, _, _ := f.verify(t, fresh, f.email, "123456", "login"); status != 200 {
					t.Fatal("fresh challenge rejected after old expiry")
				}
				f.sessions(t, 1)
			case "wrong_email", "wrong_purpose":
				emailAddr, purpose := f.email, "login"
				if name == "wrong_email" {
					emailAddr = "other@otp.invalid"
				} else {
					purpose = "recovery"
				}
				status, payload, cookies := f.verify(t, id, emailAddr, "123456", purpose)
				assertOTPRetryV2Rejected(t, status, payload, cookies)
				if row := f.state(t, id); row.Status != "pending" || row.AttemptCount != 0 {
					t.Fatal("mismatched identity/purpose changed challenge state")
				}
				f.sessions(t, 0)
				if status, _, _ := f.verify(t, id, f.email, "123456", "login"); status != 200 {
					t.Fatal("valid identity/purpose failed after mismatch")
				}
				f.sessions(t, 1)
			case "attempt_limit_then_fresh_challenge":
				for attempt := 1; attempt <= 5; attempt++ {
					status, payload, cookies := f.verify(t, id, f.email, "000000", "login")
					assertOTPRetryV2Rejected(t, status, payload, cookies)
					row := f.state(t, id)
					wantStatus := "pending"
					if attempt == 5 {
						wantStatus = "revoked"
					}
					if row.AttemptCount != attempt || row.Status != wantStatus {
						t.Fatalf("attempt %d persisted facts=%#v", attempt, row)
					}
				}
				status, payload, cookies := f.verify(t, id, f.email, "123456", "login")
				assertOTPRetryV2Rejected(t, status, payload, cookies)
				if f.state(t, id).AttemptCount != 5 {
					t.Fatal("revoked challenge continues accepting attempts")
				}
				f.sessions(t, 0)
				fresh := f.challenge(t, f.email)
				if status, _, _ := f.verify(t, fresh, f.email, "123456", "login"); status != 200 {
					t.Fatal("attempt cap revoked the entire account instead of the challenge")
				}
				f.sessions(t, 1)
			case "single_consumption":
				if status, payload, cookies := f.verify(t, id, f.email, "123456", "login"); status != 200 || !hasOTPRetryV2SessionCookie(cookies) || responseData(t, payload)["agent_id"] != "101" {
					t.Fatal("first verification did not establish the expected session")
				}
				for _, code := range []string{"123456", "000000"} {
					status, payload, cookies := f.verify(t, id, f.email, code, "login")
					assertOTPRetryV2Rejected(t, status, payload, cookies)
				}
				if row := f.state(t, id); row.Status != "consumed" || row.AttemptCount != 0 {
					t.Fatal("consumption/replay facts changed")
				}
				f.sessions(t, 1)
			case "concurrent_verify", "concurrent_wrong_codes":
				type result struct {
					status  int
					payload map[string]interface{}
					cookies [][]byte
				}
				code, n := "123456", 8
				if name == "concurrent_wrong_codes" {
					code, n = "000000", 5
				}
				results := make(chan result, n)
				gate := make(chan struct{})
				var workers sync.WaitGroup
				for i := 0; i < n; i++ {
					workers.Add(1)
					go func() {
						defer workers.Done()
						<-gate
						status, payload, cookies := f.verify(t, id, f.email, code, "login")
						results <- result{status, payload, cookies}
					}()
				}
				close(gate)
				workers.Wait()
				close(results)
				successes := 0
				for response := range results {
					if response.status == 200 {
						successes++
						if responseData(t, response.payload)["agent_id"] != "101" || !hasOTPRetryV2SessionCookie(response.cookies) {
							t.Fatal("success lacks fixture session")
						}
					} else {
						assertOTPRetryV2Rejected(t, response.status, response.payload, response.cookies)
					}
				}
				row := f.state(t, id)
				if name == "concurrent_verify" {
					if successes != 1 || row.Status != "consumed" || row.AttemptCount != 0 {
						t.Fatalf("concurrent consumption successes=%d row=%#v", successes, row)
					}
					f.sessions(t, 1)
				} else {
					if successes != 0 || row.Status != "revoked" || row.AttemptCount != 5 {
						t.Fatalf("concurrent wrong attempts successes=%d row=%#v", successes, row)
					}
					f.sessions(t, 0)
				}
			case "request_limit":
				for i := 1; i < 5; i++ {
					f.challenge(t, f.email)
				}
				status, payload, _ := performJSON(t, f.http, http.MethodPost, "/api/v2/auth/email/challenges", createEmailChallengeRequest{Email: f.email})
				if status != 429 || responseErrorCode(t, payload) != "EMAIL_RATE_LIMITED" {
					t.Fatalf("sixth challenge not rate limited: %d %#v", status, payload)
				}
				var count int64
				if err := f.db.Table("v2_email_challenges").Count(&count).Error; err != nil || count != 5 {
					t.Fatalf("rate rejection inserted a challenge: count=%d err=%v", count, err)
				}
				f.sessions(t, 0)
			case "unknown_email_does_not_create_identity":
				unknown := "unknown@otp.invalid"
				unknownID := f.challenge(t, unknown)
				status, payload, cookies := f.verify(t, unknownID, unknown, "123456", "login")
				assertOTPRetryV2Rejected(t, status, payload, cookies)
				if row := f.state(t, unknownID); row.SubjectAgentID != nil || row.Status != "pending" {
					t.Fatal("unknown email acquired an identity")
				}
				var count int64
				if err := f.db.Table("agents").Count(&count).Error; err != nil || count != 1 {
					t.Fatalf("unknown login created an agent: count=%d err=%v", count, err)
				}
				f.sessions(t, 0)
			}
		})
	}
}
