// Code generated by Kitex v0.16.1. DO NOT EDIT.

package commissionservice

import (
	"context"
	commission "eigenflux_server/kitex_gen/eigenflux/commission"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetIndexSnapshot": kitex.NewMethodInfo(
		getIndexSnapshotHandler,
		newCommissionServiceGetIndexSnapshotArgs,
		newCommissionServiceGetIndexSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListActiveIndexSnapshots": kitex.NewMethodInfo(
		listActiveIndexSnapshotsHandler,
		newCommissionServiceListActiveIndexSnapshotsArgs,
		newCommissionServiceListActiveIndexSnapshotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	commissionServiceServiceInfo                = NewServiceInfo()
	commissionServiceServiceInfoForClient       = NewServiceInfoForClient()
	commissionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return commissionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return commissionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return commissionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CommissionService"
	handlerType := (*commission.CommissionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "commission",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getIndexSnapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*commission.CommissionServiceGetIndexSnapshotArgs)
	realResult := result.(*commission.CommissionServiceGetIndexSnapshotResult)
	success, err := handler.(commission.CommissionService).GetIndexSnapshot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommissionServiceGetIndexSnapshotArgs() interface{} {
	return commission.NewCommissionServiceGetIndexSnapshotArgs()
}

func newCommissionServiceGetIndexSnapshotResult() interface{} {
	return commission.NewCommissionServiceGetIndexSnapshotResult()
}

func listActiveIndexSnapshotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*commission.CommissionServiceListActiveIndexSnapshotsArgs)
	realResult := result.(*commission.CommissionServiceListActiveIndexSnapshotsResult)
	success, err := handler.(commission.CommissionService).ListActiveIndexSnapshots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommissionServiceListActiveIndexSnapshotsArgs() interface{} {
	return commission.NewCommissionServiceListActiveIndexSnapshotsArgs()
}

func newCommissionServiceListActiveIndexSnapshotsResult() interface{} {
	return commission.NewCommissionServiceListActiveIndexSnapshotsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetIndexSnapshot(ctx context.Context, req *commission.GetIndexSnapshotReq) (r *commission.GetIndexSnapshotResp, err error) {
	var _args commission.CommissionServiceGetIndexSnapshotArgs
	_args.Req = req
	var _result commission.CommissionServiceGetIndexSnapshotResult
	if err = p.c.Call(ctx, "GetIndexSnapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListActiveIndexSnapshots(ctx context.Context, req *commission.ListActiveIndexSnapshotsReq) (r *commission.ListActiveIndexSnapshotsResp, err error) {
	var _args commission.CommissionServiceListActiveIndexSnapshotsArgs
	_args.Req = req
	var _result commission.CommissionServiceListActiveIndexSnapshotsResult
	if err = p.c.Call(ctx, "ListActiveIndexSnapshots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
